const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const rawCsv = `SAF Code,Inventory Category,Sub Category,Element,Brand,Model,Size/LWH,Serial No,Allocated,Allocated,Remaining,Total Qty,Allocated To,Location,Zone,Condition,Throw Ratio,Remarks,,Serial Number_FAEM,,,,,,,,,,,,,,,,
Na,Production,Display,Easel,Na,Na,57X20,Na,0,,9,9,,Delhi Warehouse,To be defined,Ok,,Ok,,NaEasel57X20,,,,,,,,,,,,,,,,
Na,Furniture,Stool,White Stool,Na,Na,12X18,Na,0,,19,19,,Delhi Warehouse,To be defined,Ok,,Ok,,NaWhite Stool12X18,,,,,,,,,,,,,,,,
Na,Furniture,Stool,Blue Iron Stool,Na,Na,12X18,Na,0,,5,5,,Delhi Warehouse,To be defined,Ok,,Ok,,NaBlue Iron Stool12X18,,,,,,,,,,,,,,,,
Na,Furniture,Stool,Black Iron Stool,Na,Na,12X18,Na,0,,4,4,,Delhi Warehouse,To be defined,Ok,,Ok,,NaBlack Iron Stool12X18,,,,,,,,,,,,,,,,
Na,Furniture,Storage,Shelf,Na,Na,51X35X16,Na,0,,3,3,,Delhi Warehouse,To be defined,Ok,,Ok,,NaShelf51X35X16,,,,,,,,,,,,,,,,
Na,Furniture,Bench,Mango Wood Bench,Na,Na,18X51X18,Na,0,,6,6,,Delhi Warehouse,To be defined,Ok,,Ok,,NaMango Wood Bench18X51X18,,,,,,,,,,,,,,,,
Na,Furniture,Bench,Neo Bench - Black Stained Ashwood,Na,Na,18X47X12,Na,0,,4,4,,Delhi Warehouse,To be defined,Ok,,Ok,,NaNeo Bench - Black Stained Ashwood18X47X12,,,,,,,,,,,,,,,,
Na,Furniture,Bench,Bench 2023 PWD,Na,Na,16X47X12,Na,0,,7,7,,Delhi Warehouse,To be defined,Ok,,Ok,,NaBench 2023 PWD16X47X12,,,,,,,,,,,,,,,,
Na,Production,Display,High Raise Light Box,Na,Na,50X15X13,Na,0,,5,5,,Delhi Warehouse,To be defined,Ok,,Ok,,NaHigh Raise Light Box50X15X13,,,,,,,,,,,,,,,,
Na,Furniture,Side table,Iron Round Side Table,Na,Na,17X17X21,Na,0,,4,4,,Delhi Warehouse,To be defined,Ok,,Ok,,NaIron Round Side Table17X17X21,,,,,,,,,,,,,,,,
Na,Furniture,Table,Iron Glass Top Table,Na,Na,20X20X20,Na,0,,1,1,,Delhi Warehouse,To be defined,Ok,,Ok,,NaIron Glass Top Table20X20X20,,,,,,,,,,,,,,,,
Na,Furniture,Stool,Sono Stool - Natural Oakwood,Na,Na,18X11X11,Na,0,,2,2,,Delhi Warehouse,To be defined,Ok,,Ok,,NaSono Stool - Natural Oakwood18X11X11,,,,,,,,,,,,,,,,
Na,Furniture,Table,Iron Glass Top Table 2,Na,Na,18X36X18,Na,0,,1,1,,Delhi Warehouse,To be defined,Ok,,Ok,,NaIron Glass Top Table 218X36X18,,,,,,,,,,,,,,,,
Na,Furniture,Chair,Pouf,Na,Na,14X12X12,Na,0,,4,4,,Delhi Warehouse,To be defined,Ok,,Ok,,NaPouf14X12X12,,,,,,,,,,,,,,,,
Na,Furniture,Bench,Wooden Bench,Na,Na,19X47X14,Na,0,,4,4,,Delhi Warehouse,To be defined,Ok,,Ok,,NaWooden Bench19X47X14,,,,,,,,,,,,,,,,
Na,Furniture,Storage,Cabinet,Na,Na,65X18X8,Na,0,,4,4,,Delhi Warehouse,To be defined,Ok,,Ok,,NaCabinet65X18X8,,,,,,,,,,,,,,,,
Na,Furniture,Storage,Glass Cabinet,Na,Na,59X38X15,Na,0,,1,1,,Delhi Warehouse,To be defined,Ok,,Ok,,NaGlass Cabinet59X38X15,,,,,,,,,,,,,,,,
Na,Furniture,Storage,Glass Cabinet 2,Na,Na,59X22X22,Na,0,,1,1,,Delhi Warehouse,To be defined,Ok,,Ok,,NaGlass Cabinet 259X22X22,,,,,,,,,,,,,,,,
Na,Furniture,Table,White Table 1,Na,Na,29X47X24,Na,0,,6,6,,Delhi Warehouse,To be defined,Ok,,Ok,,NaWhite Table 129X47X24,,,,,,,,,,,,,,,,
Na,Furniture,Table,White Table 2,Na,Na,30X62X24,Na,0,,1,1,,Delhi Warehouse,To be defined,Ok,,Ok,,NaWhite Table 230X62X24,,,,,,,,,,,,,,,,
Na,Furniture,Table,White Table 3,Na,Na,30X54X30,Na,0,,7,7,,Delhi Warehouse,To be defined,Ok,,Ok,,NaWhite Table 330X54X30,,,,,,,,,,,,,,,,
Na,Furniture,Table,White Table 3,Na,Na,29X79X30,Na,0,,1,1,,Delhi Warehouse,To be defined,Ok,,Ok,,NaWhite Table 329X79X30,,,,,,,,,,,,,,,,
Na,Furniture,Storage,White Drawer,Na,Na,24X17X21,Na,0,,13,13,,Delhi Warehouse,To be defined,Ok,,Ok,,NaWhite Drawer24X17X21,,,,,,,,,,,,,,,,
Crompton,Appliance,Fan,White Pedestal Fan,Crompton,Na,Na,Na,0,,1,1,,Defence Colony,To be defined,Ok,,Ok,,CromptonWhite Pedestal FanNa,,,,,,,,,,,,,,,,
Na,Misc.,Board,Memo Board Black,IKEA,Na,40x60,Na,0,,4,4,,Defence Colony,To be defined,Ok,,2 ground floor + 2 first floor hall,,NaMemo Board Black40x60,,,,,,,,,,,,,,,,
Na,Misc.,Storage,Shelving Unit,IKEA,Na,60x27x140,Na,0,,2,2,,Defence Colony,To be defined,Ok,,Kitchen,,NaShelving Unit60x27x140,,,,,,,,,,,,,,,,
Na,Misc.,Storage,Box With Castors And Lid White,IKEA,Na,38x51x37,Na,0,,5,5,,Defence Colony,To be defined,Ok,,Storage,,NaBox With Castors And Lid White38x51x37,,,,,,,,,,,,,,,,
Na,Misc.,Board,Whiteboard Noticeboard With Castors,IKEA,Na,70x180,Na,0,,3,3,,Defence Colony,To be defined,Ok,,1 Ground floor + 2 First Floor,,NaWhiteboard Noticeboard With Castors70x180,,,,,,,,,,,,,,,,
Na,Misc.,Storage,Box With Lid Transparent,IKEA,Na,57x39x28 cm/45,Na,0,,9,9,,Defence Colony,To be defined,Ok,,Storage,,NaBox With Lid Transparent57x39x28 cm/45,,,,,,,,,,,,,,,,
Na,Misc.,Storage,Box With Lid White,IKEA,Na,38x51x30 cm,Na,0,,10,10,,Defence Colony,To be defined,Ok,,Storage,,NaBox With Lid White38x51x30 cm,,,,,,,,,,,,,,,,
Na,Misc.,Storage,Desk Organiser White,IKEA,Na,25x20 cm,Na,0,,4,4,,Defence Colony,To be defined,Ok,,1 TLB + 1 Production extension + 2 first floor hall,,NaDesk Organiser White25x20 cm,,,,,,,,,,,,,,,,
Na,Furniture,Dining table,Zyle Dining Table,Na,Na,5.25'X2.5'X2.5',Na,0,,1,1,,Delhi Warehouse,To be defined,Ok,,Na,,NaZyle Dining Table5.25'X2.5'X2.5',,,,,,,,,,,,,,,,
Na,Furniture,Board,Pegboard Combination White,Ikea,Na,56x56,Na,0,,6,6,,Defence Colony,To be defined,Ok,,Each Room,,NaPegboard Combination White56x56,,,,,,,,,,,,,,,,
Na,Furniture,Shelf,Display Shelf White,Ikea,Na,60,Na,0,,4,4,,Defence Colony,To be defined,Ok,,MiNaal's Room,,NaDisplay Shelf White60,,,,,,,,,,,,,,,,
Na,Furniture,Desk,Desk White,Ikea,Na,160x80,Na,0,,2,2,,Defence Colony,To be defined,Ok,,First Floor Room,,NaDesk White160x80,,,,,,,,,,,,,,,,
Na,Furniture,Drawer,Drawer Unit White,Ikea,Na,34x56,Na,0,,4,4,,Defence Colony,To be defined,Ok,,2 In production extension & 2 in first floor hall,,NaDrawer Unit White34x56,,,,,,,,,,,,,,,,
Na,Furniture,Drawer,Drawer Unit 3 On Castors White,Ikea,Na,40x47x56,Na,0,,8,8,,Defence Colony,To be defined,Ok,,4 ground floor + 4 first floor,,NaDrawer Unit 3 On Castors White40x47x56,,,,,,,,,,,,,,,,
Na,Furniture,Table,Table Beige White,Ikea,Na,80x80,Na,0,,1,1,,Defence Colony,To be defined,Ok,,MiNaal's Room,,NaTable Beige White80x80,,,,,,,,,,,,,,,,
Na,Furniture,Desk,Desk White 1,Ikea,Na,120x60,Na,0,,1,1,,Defence Colony,To be defined,Ok,,Tlb,,NaDesk White 1120x60,,,,,,,,,,,,,,,,
Na,Furniture,Desk,Desk White 2,Ikea,Na,200x60,Na,0,,14,14,,Defence Colony,To be defined,Ok,,1 TLB + 4 production extended + 4 first floor hall + rest 6 TBD,,NaDesk White 2200x60,,,,,,,,,,,,,,,,
Na,Furniture,Drawer,Desk White 3,Ikea,Na,140x60,Na,0,,3,3,,Defence Colony,To be defined,Ok,,2 fiNance + Neelangshu,,NaDesk White 3140x60,,,,,,,,,,,,,,,,
Na,Furniture,Wall cabinet,Wall Cabinet White With 1 Shelf,Ikea,Na,60x32x60,Na,0,,5,5,,Defence Colony,To be defined,Ok,,FiNance,,NaWall Cabinet White With 1 Shelf60x32x60,,,,,,,,,,,,,,,,
Na,Furniture,Table,Table White,Ikea,Na,100x60,Na,0,,7,7,,Defence Colony,To be defined,Ok,,First floor hall,,NaTable White100x60,,,,,,,,,,,,,,,,
Na,Furniture,Bookcase,Bookcase White,Ikea,Na,80x28x237,Na,0,,2,2,,Defence Colony,To be defined,Ok,,MiNaal's room,,NaBookcase White80x28x237,,,,,,,,,,,,,,,,
Na,Furniture,Cabinet combiNation,Cabinet Combination Grey,Ikea,Na,120x35x92,Na,0,,5,5,,Defence Colony,To be defined,Ok,,Smriti's room,,NaCabinet Combination Grey120x35x92,,,,,,,,,,,,,,,,
Na,Furniture,Wall shelf,Wall Shelf White,Ikea,Na,120x30,Na,0,,2,2,,Defence Colony,To be defined,Ok,,MiNaal's room,,NaWall Shelf White120x30,,,,,,,,,,,,,,,,
Na,Furniture,Storage combiNation with doors,Storage Combination With Doors White,Ikea,Na,45x47x167,Na,0,,2,2,,Defence Colony,To be defined,Ok,,Production extension,,NaStorage Combination With Doors White45x47x167,,,,,,,,,,,,,,,,
Na,Furniture,Bookcase combiNation w glass doors,Bookcase Combination Glass Doors Oak Effect Clear Glass,Ikea,Na,120x30x202,Na,0,,1,1,,Defence Colony,To be defined,Ok,,MiNaal's room,,NaBookcase Combination Glass Doors Oak Effect Clear Glass120x30x202,,,,,,,,,,,,,,,,
Na,Furniture,High,High Rise Chair Barchair,Spin,Na,17X17X36,Na,0,,3,3,,Defence Colony,To be defined,Ok,,Production extension,,NaHigh Rise Chair Barchair17X17X36,,,,,,,,,,,,,,,,
Na,Furniture,Drawer,Ikea Drawer 2023 Skm Lounge,Ikea,Na,24X14X22,Na,0,,2,2,,Defence Colony,To be defined,Ok,,Tlb,,NaIkea Drawer 2023 Skm Lounge24X14X22,,,,,,,,,,,,,,,,
Na,Furniture,Stool,Neo Mini Stool Black Stained Oakwood,Ikea,Na,12X18,Na,0,,1,1,,Defence Colony,To be defined,Ok,,Na,,NaNeo Mini Stool Black Stained Oakwood12X18,,,,,,,,,,,,,,,,
Na,Furniture,Stool,Sono Stool - Natural Oakwood,Ikea,Na,11X11X18,Na,0,,4,4,,Defence Colony,To be defined,Ok,,Na,,NaSono Stool - Natural Oakwood11X11X18,,,,,,,,,,,,,,,,
Na,Furniture,Chair,Solimo Black Chair,Solimo,Na,20X16X31,Na,0,,6,6,,Defence Colony,To be defined,Ok,,Na,,NaSolimo Black Chair20X16X31,,,,,,,,,,,,,,,,
Na,Furniture,Chair,Ikea Black foldable Chair,Ikea,Na,15X13X30,Na,0,,5,5,,Defence Colony,To be defined,Ok,,Na,,NaIkea Black foldable Chair15X13X30,,,,,,,,,,,,,,,,
Na,Furniture,Beans,Bean Bags,Amozon,Na,Na,Na,0,,5,5,,Defence Colony,To be defined,Ok,,Na,,NaBean BagsNa,,,,,,,,,,,,,,,,
Na,Furniture,Table,Ikea Black Table,Ikea,Na,39X24X29,Na,0,,5,5,,Defence Colony,To be defined,Ok,,Na,,NaIkea Black Table39X24X29,,,,,,,,,,,,,,,,
Na,Furniture,Trolley,Side Trolleys,Ikea,Na,14X10X31,Na,0,,2,2,,Defence Colony,To be defined,Ok,,Na,,NaSide Trolleys14X10X31,,,,,,,,,,,,,,,,
Na,Furniture,Couch,Arc Lounger,Spin,Na,7'X2.5'X2.5',Na,0,,1,1,,Defence Colony,To be defined,Ok,,Ok,,NaArc Lounger7'X2.5'X2.5',,,,,,,,,,,,,,,,
Na,Furniture,Table,Red Desk,Spin,Na,5,Na,0,,1,1,,Defence Colony,To be defined,Ok,,Ok,,NaRed Desk5,,,,,,,,,,,,,,,,
Na,Furniture,Mudda,Jute Mudda 1,Na,Na,"16""X16""",Na,0,,4,4,,Delhi Warehouse,To be defined,Ok,,,,"NaJute Mudda 116""X16""",,,,,,,,,,,,,,,,
Na,Furniture,Mudda,Jute Mudda 2,Na,Na,"13""X14""",Na,0,,6,6,,Delhi Warehouse,To be defined,Ok,,,,"NaJute Mudda 213""X14""",,,,,,,,,,,,,,,,
Na,Furniture,Mudda,Jute Mudda 3,Na,Na,"15""x12""",Na,0,,5,5,,Delhi Warehouse,To be defined,Ok,,,,"NaJute Mudda 315""x12""",,,,,,,,,,,,,,,,
Na,Furniture,Mudda,Jute Mudda 4,Na,Na,"13""X9""",Na,0,,2,2,,Delhi Warehouse,To be defined,Ok,,,,"NaJute Mudda 413""X9""",,,,,,,,,,,,,,,,
Na,Lights,Lights,Spot Lamp,Bdcl,Na,Na,Na,0,,9,9,,Delhi Warehouse,To be defined,Bieng Check,,,,NaSpot LampNa,,,,,,,,,,,,,,,,
Na,Lights,Lights,Spot Lamp,Bdcl,Na,Na,Na,0,,12,12,,Delhi Warehouse,To be defined,Bieng Check,,,,NaSpot LampNa,,,,,,,,,,,,,,,,
Na,Lights,Lights,Sunglow Zoomable,Sunglow,Na,Na,Na,0,,21,21,,Delhi Warehouse,To be defined,Bieng Check,,,,NaSunglow ZoomableNa,,,,,,,,,,,,,,,,
Na,Lights,Lights,Sunglow Framing,Sunglow,Na,Na,Na,0,,33,33,,Delhi Warehouse,To be defined,Bieng Check,,,,NaSunglow FramingNa,,,,,,,,,,,,,,,,
Na,Lights,Lights,Spot Lamp,Bdcl,Na,Na,Na,0,,17,17,,Delhi Warehouse,To be defined,Bieng Check,,,,NaSpot LampNa,,,,,,,,,,,,,,,,
Na,Lights,Lights,Small Lamp,Bdcl,Na,Na,Na,0,,19,19,,Delhi Warehouse,To be defined,Bieng Check,,,,NaSmall LampNa,,,,,,,,,,,,,,,,
Na,Lights,Lights,Spot Lamp,Bdcl,Na,Na,Na,0,,15,15,,Delhi Warehouse,To be defined,Bieng Check,,,,NaSpot LampNa,,,,,,,,,,,,,,,,
Na,Lights,Lights,Spot Lamp,Bdcl,Na,Na,Na,0,,15,15,,Delhi Warehouse,To be defined,Bieng Check,,,,NaSpot LampNa,,,,,,,,,,,,,,,,
Na,Lights,Lights,Track Spot Light,Bdcl,Na,Na,Na,0,,55,55,,Delhi Warehouse,To be defined,Bieng Check,,,,NaTrack Spot LightNa,,,,,,,,,,,,,,,,
Na,Lights,Lights,Track Spot Light,Bdcl,Na,Na,Na,0,,55,55,,Delhi Warehouse,To be defined,Bieng Check,,,,NaTrack Spot LightNa,,,,,,,,,,,,,,,,
Na,Lights,Lights,Track Spot Light,Bdcl,Na,Na,Na,0,,55,55,,Delhi Warehouse,To be defined,Bieng Check,,,,NaTrack Spot LightNa,,,,,,,,,,,,,,,,
Na,Lights,Lights,Track Spot Light,Bdcl,Na,Na,Na,0,,55,55,,Delhi Warehouse,To be defined,Bieng Check,,,,NaTrack Spot LightNa,,,,,,,,,,,,,,,,
Na,Lights,Lights,Track Spot Light,Bdcl,Na,Na,Na,0,,55,55,,Delhi Warehouse,To be defined,Bieng Check,,,,NaTrack Spot LightNa,,,,,,,,,,,,,,,,
Na,Lights,Lights,Track Spot Light,Bdcl,Na,Na,Na,0,,12,12,,Delhi Warehouse,To be defined,Bieng Check,,,,NaTrack Spot LightNa,,,,,,,,,,,,,,,,
Na,Lights,Lights,Sunglow Framing,Sunglow,Na,Na,Na,0,,4,4,,Delhi Warehouse,To be defined,Bieng Check,,,,NaSunglow FramingNa,,,,,,,,,,,,,,,,
Na,Lights,Lights,Sunglow Zoomable,Sunglow,Na,Na,Na,0,,7,7,,Delhi Warehouse,To be defined,Bieng Check,,,,NaSunglow ZoomableNa,,,,,,,,,,,,,,,,
Na,Technical,Screen,Projection Screen,Na,Na,12.5'x7.5',Na,0,,1,1,,Delhi Warehouse,To be defined,Ok,,Not Ok,,NaProjection Screen12.5'x7.5',,,,,,,,,,,,,,,,
Na,Technical,Screen,Projection Screen,Na,Na,10'x6.5',Na,0,,2,2,,Delhi Warehouse,To be defined,Ok,,Not Ok,,NaProjection Screen10'x6.5',,,,,,,,,,,,,,,,
Na,Production,Tent,Tent Material,Na,Na,Na,Na,0,,#VALUE!,Na,,Goa Warehouse,Zone A,Ok,,Ok,,NaTent MaterialNa,,,,,,,,,,,,,,,,
Na,Production,Tools,Ladder Self Standing,Na,Na,12',Na,0,,8,8,,Goa Warehouse,Zone I,Ok,,Ok,,NaLadder Self Standing12',,,,,,,,,,,,,,,,
Na,Production,Tools,Ladder,Na,Na,12',Na,0,,1,1,,Goa Warehouse,Zone I,Ok,,Ok,,NaLadder12',,,,,,,,,,,,,,,,
Na,Production,Tools,Ladder Self Standing,Na,Na,10',Na,0,,10,10,,Goa Warehouse,Zone I,Ok,,Ok,,NaLadder Self Standing10',,,,,,,,,,,,,,,,
Na,Production,Tools,Ladder Self Standing,Na,Na,8',Na,0,,7,7,,Goa Warehouse,Zone I,Ok,,Ok,,NaLadder Self Standing8',,,,,,,,,,,,,,,,
Na,Production,Platform,G20 1,Na,Na,"3'X4'X4""",Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,"NaG20 13'X4'X4""",,,,,,,,,,,,,,,,
Na,Production,Platform,G20 2,Na,Na,3'X3'X3',Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,NaG20 23'X3'X3',,,,,,,,,,,,,,,,
Na,Production,Platform,G20 3,Na,Na,2'X2'X3',Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,NaG20 32'X2'X3',,,,,,,,,,,,,,,,
Na,Production,Platform,G20 4,Na,Na,"4'X4'X4""",Na,0,,2,2,,Goa Warehouse,ZoneB,Ok,,Ok,,"NaG20 44'X4'X4""",,,,,,,,,,,,,,,,
Na,Production,Platform,G20 5,Na,Na,"8'X5'X4""",Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,"NaG20 58'X5'X4""",,,,,,,,,,,,,,,,
Na,Production,Platform,G20 6,Na,Na,"8'X6'X4""",Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,"NaG20 68'X6'X4""",,,,,,,,,,,,,,,,
Na,Production,Platform,G20 7,Na,Na,8'X6'X6',Na,0,,6,6,,Goa Warehouse,ZoneB,Ok,,Ok,,NaG20 78'X6'X6',,,,,,,,,,,,,,,,
Na,Production,Platform,G20 8,Na,Na,4.7'X2'X1.5',Na,0,,6,6,,Goa Warehouse,ZoneB,Ok,,Ok,,NaG20 84.7'X2'X1.5',,,,,,,,,,,,,,,,
Na,Production,Platform,G20 9,Na,Na,4'X2'X2',Na,0,,6,6,,Goa Warehouse,ZoneB,Ok,,Ok,,NaG20 94'X2'X2',,,,,,,,,,,,,,,,
Na,Production,Platform,G20 10,Na,Na,"50""X36""X30""",Na,0,,2,2,,Goa Warehouse,ZoneB,Ok,,Ok,,"NaG20 1050""X36""X30""",,,,,,,,,,,,,,,,
Na,Production,Platform,G20 11,Na,Na,4'X4'X5',Na,0,,3,3,,Goa Warehouse,ZoneB,Ok,,Ok,,NaG20 114'X4'X5',,,,,,,,,,,,,,,,
Na,Production,Platform,G20 12,Na,Na,4'X2'X1',Na,0,,3,3,,Goa Warehouse,ZoneB,Ok,,Ok,,NaG20 124'X2'X1',,,,,,,,,,,,,,,,
Na,Production,Platform,G20 13,Na,Na,8'X2.5'X2',Na,0,,3,3,,Goa Warehouse,ZoneB,Ok,,Ok,,NaG20 138'X2.5'X2',,,,,,,,,,,,,,,,
Na,Production,Platform,G20 14,Na,Na,"83""X36""X24""",Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,"NaG20 1483""X36""X24""",,,,,,,,,,,,,,,,
Na,Production,Platform,G20 15,Na,Na,4'X2'X1.5',Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,NaG20 154'X2'X1.5',,,,,,,,,,,,,,,,
Na,Production,Platform,G20 16,Na,Na,7'X2'X1,Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,NaG20 167'X2'X1,,,,,,,,,,,,,,,,
Na,Production,Platform,G20 17,Na,Na,6'X3'X1,Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,NaG20 176'X3'X1,,,,,,,,,,,,,,,,
Na,Production,Platform,G20 18,Na,Na,"6.9'X1'X6""",Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,"NaG20 186.9'X1'X6""",,,,,,,,,,,,,,,,
Na,Production,Platform,G20 19,Na,Na,"10.9'X1'X6""",Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,"NaG20 1910.9'X1'X6""",,,,,,,,,,,,,,,,
Na,Production,Platform,G20 20,Na,Na,"12'X3'X4""",Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,"NaG20 2012'X3'X4""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,Box one side open 47,Na,Na,1'X1'X1',Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,NaBox one side open 471'X1'X1',,,,,,,,,,,,,,,,
Na,Production,Pedestal,Box one side white 21,Na,Na,1'X1'X1',Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,NaBox one side white 211'X1'X1',,,,,,,,,,,,,,,,
Na,Production,Pedestal,G20 Box 22,Na,Na,1'X1'X2.5',Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,NaG20 Box 221'X1'X2.5',,,,,,,,,,,,,,,,
Na,Production,Pedestal,G20 Box 23,Na,Na,1'X1'X3.5',Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,NaG20 Box 231'X1'X3.5',,,,,,,,,,,,,,,,
Na,Production,Pedestal,G20 Box 24,Na,Na,1'X1'X3',Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,NaG20 Box 241'X1'X3',,,,,,,,,,,,,,,,
Na,Production,Pedestal,G20 Box 25,Na,Na,1'X1'X1.5',Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,NaG20 Box 251'X1'X1.5',,,,,,,,,,,,,,,,
Na,Production,Pedestal,G20 Box 26,Na,Na,1.5'X1.5'X1',Na,0,,2,2,,Goa Warehouse,ZoneB,Ok,,Ok,,NaG20 Box 261.5'X1.5'X1',,,,,,,,,,,,,,,,
Na,Production,Pedestal,G20 Box 27,Na,Na,1.5'X1.5'X1.5',Na,0,,2,2,,Goa Warehouse,ZoneB,Ok,,Ok,,NaG20 Box 271.5'X1.5'X1.5',,,,,,,,,,,,,,,,
Na,Production,Pedestal,G20 Box 28,Na,Na,1.5'X1.5'X2',Na,0,,3,3,,Goa Warehouse,ZoneB,Ok,,Ok,,NaG20 Box 281.5'X1.5'X2',,,,,,,,,,,,,,,,
Na,Production,Pedestal,G20 Box 29,Na,Na,"2'X2'X6""",Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,"NaG20 Box 292'X2'X6""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,G20 Cylinderical 30,Na,Na,"8""X1'",Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,"NaG20 Cylinderical 308""X1'",,,,,,,,,,,,,,,,
Na,Production,Pedestal,G20 Cylinderical 31,Na,Na,"1.3'X6""",Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,"NaG20 Cylinderical 311.3'X6""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,G20 Cylinderical with stand 32,Na,Na,1.9'X2.5',Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,NaG20 Cylinderical with stand 321.9'X2.5',,,,,,,,,,,,,,,,
Na,Production,Pedestal,G20 L Shaped 33,Na,Na,"1'X1'X4""",Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,"NaG20 L Shaped 331'X1'X4""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,G20 Box with Stand 34,Na,Na,1'X1'X5',Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,NaG20 Box with Stand 341'X1'X5',,,,,,,,,,,,,,,,
Na,Production,Pedestal,G20 Box 35,Na,Na,3'X3'X3',Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,NaG20 Box 353'X3'X3',,,,,,,,,,,,,,,,
Na,Production,Pedestal,G20 Box 36,Na,Na,"11""X11""X4""",Na,0,,3,3,,Goa Warehouse,ZoneB,Ok,,Ok,,"NaG20 Box 3611""X11""X4""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,G20 Box 37,Na,Na,"9""X9""X8""",Na,0,,5,5,,Goa Warehouse,ZoneB,Ok,,Ok,,"NaG20 Box 379""X9""X8""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,G20 Box 38,Na,Na,"5""X5""X1'",Na,0,,6,6,,Goa Warehouse,ZoneB,Ok,,Ok,,"NaG20 Box 385""X5""X1'",,,,,,,,,,,,,,,,
Na,Production,Pedestal,G20 Box 39,Na,Na,8'X3'X4',Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,NaG20 Box 398'X3'X4',,,,,,,,,,,,,,,,
Na,Production,Pedestal,G20 Box 40,Na,Na,9'X2'X4',Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,NaG20 Box 409'X2'X4',,,,,,,,,,,,,,,,
Na,Production,Branding,G20-41,Na,Na,1'X1.5'X7.10',Na,0,,5,5,,Goa Warehouse,ZoneB,Ok,,Ok,,NaG20-411'X1.5'X7.10',,,,,,,,,,,,,,,,
Na,Production,Stand,Easel Stand-5ft,Na,Na,"1'10"" Span | 5' height",Na,0,,49,49,,Goa Warehouse,ZoneB,Ok,,Ok,,"NaEasel Stand-5ft1'10"" Span | 5' height",,,,,,,,,,,,,,,,
Na,Production,Stand,Tripod Metal Stand,Na,Na,3'span X 5' height,Na,0,,21,21,,Goa Warehouse,Zone I,Ok,,Ok,,NaTripod Metal Stand3'span X 5' height,,,,,,,,,,,,,,,,
Na,Production,Misc.,Black Umbrella,Na,Na,6' (h) | 4' Span,Na,0,,2,2,,Goa Warehouse,Zone D,Ok,,Ok,,NaBlack Umbrella6' (h) | 4' Span,,,,,,,,,,,,,,,,
Na,Production,Misc.,Black Umbrella base,Na,Na,Na,Na,0,,2,2,,Goa Warehouse,Zone D,Ok,,Ok,,NaBlack Umbrella baseNa,,,,,,,,,,,,,,,,
Na,Production,Misc.,White Umbrella,Na,Na,6' (h) | 4' Span,Na,0,,1,1,,Goa Warehouse,Zone D,Ok,,Ok,,NaWhite Umbrella6' (h) | 4' Span,,,,,,,,,,,,,,,,
Na,Production,Misc.,Coat Stand,Na,Na,5',Na,0,,2,2,,Goa Warehouse,Zone D,Ok,,Ok,,NaCoat Stand5',,,,,,,,,,,,,,,,
Na,Production,Branding,White Acrylic Self Standing Branding,Na,Na,"28""X12""",Na,0,,5,5,,Goa Warehouse,Zone A,Ok,,Ok,,"NaWhite Acrylic Self Standing Branding28""X12""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,G20 Box 42,Na,Na,1.5'X1.5'X2',Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,NaG20 Box 421.5'X1.5'X2',,,,,,,,,,,,,,,,
Na,Production,Pedestal,G20 Box 43,Na,Na,1.5'X1.5'X1.5',Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,NaG20 Box 431.5'X1.5'X1.5',,,,,,,,,,,,,,,,
Na,Production,Pedestal,G20 Box 44,Na,Na,1.5'X1.5'X1',Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,NaG20 Box 441.5'X1.5'X1',,,,,,,,,,,,,,,,
Na,Production,Pedestal,G20 Box 45,Na,Na,2'X1'X1',Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,NaG20 Box 452'X1'X1',,,,,,,,,,,,,,,,
Na,Production,Pedestal,G20 Box 46,Na,Na,"5'X5'X8""",Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,"NaG20 Box 465'X5'X8""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,G20 Box 48,Na,Na,"1'X1'X4""",Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,"NaG20 Box 481'X1'X4""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,G20 49,Na,Na,1'X1',Na,0,,1,1,,Goa Warehouse,ZoneB,Ok,,Ok,,NaG20 491'X1',,,,,,,,,,,,,,,,
Na,Production,Light Box,Prints,Na,Na,"47""X67""X7""",Na,0,,13,13,,Goa Warehouse,Zone B,Ok,,Ok,,"NaPrints47""X67""X7""",,,,,,,,,,,,,,,,
Na,Production,Stand,Angluar Stand 5ft,Na,Na,1.5'X1'X5',Na,0,,33,33,,Goa Warehouse,Zone D,Ok,,Ok,,NaAngluar Stand 5ft1.5'X1'X5',,,,,,,,,,,,,,,,
Na,Production,Stand,Rectangular Stand 6ft,Na,Na,2.3'X1'X6',Na,0,,3,3,,Goa Warehouse,Zone B,Ok,,Ok,,NaRectangular Stand 6ft2.3'X1'X6',,,,,,,,,,,,,,,,
Na,Production,Stand,Rectangular Stand 7.5ft,Na,Na,2.5'X1.4'X7.5',Na,0,,2,2,,Goa Warehouse,Zone B,Ok,,Ok,,NaRectangular Stand 7.5ft2.5'X1.4'X7.5',,,,,,,,,,,,,,,,
Na,Production,Pedestal,White pedestal 1,Na,Na,1'x1'x5',Na,0,,8,8,,Goa Warehouse,Zone A,Ok,,Ok,,NaWhite pedestal 11'x1'x5',,,,,,,,,,,,,,,,
Na,Production,Pedestal,White pedestal 4,Na,Na,"1'6""x1'6"" x2'7""",Na,0,,3,3,,Goa Warehouse,Zone A,Ok,,Ok,,"NaWhite pedestal 41'6""x1'6"" x2'7""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,White pedestal 5,Na,Na,1'x1'x3',Na,0,,2,2,,Goa Warehouse,Zone A,Ok,,Ok,,NaWhite pedestal 51'x1'x3',,,,,,,,,,,,,,,,
Na,Production,Pedestal,White pedestal 6,Na,Na,"1'x1'x3'4""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaWhite pedestal 61'x1'x3'4""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,White pedestal 8,Na,Na,"1'9""x1'x3'6""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaWhite pedestal 81'9""x1'x3'6""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,White pedestal 14,Na,Na,"2'x1'6""x2'7""",Na,0,,2,2,,Goa Warehouse,Zone A,Ok,,Ok,,"NaWhite pedestal 142'x1'6""x2'7""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,White pedestal 15,Na,Na,"1'x1'x4'4""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaWhite pedestal 151'x1'x4'4""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,White pedestal 16,Na,Na,"11""x10""x4'",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaWhite pedestal 1611""x10""x4'",,,,,,,,,,,,,,,,
Na,Production,Pedestal,White pedestal 18,Na,Na,"1'x1'x2'7""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaWhite pedestal 181'x1'x2'7""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,White pedestal 19,Na,Na,1'x1'x2',Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,NaWhite pedestal 191'x1'x2',,,,,,,,,,,,,,,,
Na,Production,Pedestal,White pedestal 20,Na,Na,"1'3""x1'3""x3'2""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaWhite pedestal 201'3""x1'3""x3'2""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,White pedestal 21,Na,Na,"1'4""x1'4""x3'",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaWhite pedestal 211'4""x1'4""x3'",,,,,,,,,,,,,,,,
Na,Production,Pedestal,White pedestal 23,Na,Na,"1'6""x1'6""x3'",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaWhite pedestal 231'6""x1'6""x3'",,,,,,,,,,,,,,,,
Na,Production,Pedestal,White pedestal 24,Na,Na,2'x2'x2',Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,NaWhite pedestal 242'x2'x2',,,,,,,,,,,,,,,,
Na,Production,Pedestal,White pedestal 25,Na,Na,"2'4""x1'4""x3'",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaWhite pedestal 252'4""x1'4""x3'",,,,,,,,,,,,,,,,
Na,Production,Pedestal,White pedestal 26,Na,Na,"3'x2'x2'6""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaWhite pedestal 263'x2'x2'6""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,White pedestal 27,Na,Na,"1'7""x1'7""x1'7""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaWhite pedestal 271'7""x1'7""x1'7""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,White pedestal 28,Na,Na,"1'6""x1'6""x1'",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaWhite pedestal 281'6""x1'6""x1'",,,,,,,,,,,,,,,,
Na,Production,Pedestal,White pedestal 29,Na,Na,"1'8""x1'5""x6""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaWhite pedestal 291'8""x1'5""x6""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,White pedestal 30,Na,Na,"1'4""x1'x1'4""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaWhite pedestal 301'4""x1'x1'4""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,White pedestal 31,Na,Na,"1'7""x1'7""x6""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaWhite pedestal 311'7""x1'7""x6""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,White pedestal 32,Na,Na,"2'x1'8""x1'",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaWhite pedestal 322'x1'8""x1'",,,,,,,,,,,,,,,,
Na,Production,Pedestal,White pedestal 33,Na,Na,3'x2'x1',Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,NaWhite pedestal 333'x2'x1',,,,,,,,,,,,,,,,
Na,Production,Pedestal,Black pedestal 2,Na,Na,"1'6""x1'6""x2'",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaBlack pedestal 21'6""x1'6""x2'",,,,,,,,,,,,,,,,
Na,Production,Pedestal,Black pedestal 3,Na,Na,"1'x1'x6'8""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaBlack pedestal 31'x1'x6'8""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,Black pedestal 4,Na,Na,"1'6""x1'x4'",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaBlack pedestal 41'6""x1'x4'",,,,,,,,,,,,,,,,
Na,Production,Pedestal,Black pedestal 5,Na,Na,"1'8""x1'2""x7'3""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaBlack pedestal 51'8""x1'2""x7'3""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,Black pedestal 6,Na,Na,"1'3""x1'3""x3'3""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaBlack pedestal 61'3""x1'3""x3'3""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,Black pedestal 7,Na,Na,"1'x1'x3'6""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaBlack pedestal 71'x1'x3'6""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,Black pedestal 8,Na,Na,"1'3""x1'3""x1'7""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaBlack pedestal 81'3""x1'3""x1'7""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,Black pedestal 9,Na,Na,"2'8""x1'5""x3'4""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaBlack pedestal 92'8""x1'5""x3'4""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,Purple pedestal,Na,Na,1'X2',Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,NaPurple pedestal1'X2',,,,,,,,,,,,,,,,
Na,Production,Pedestal,Chipboard pedestal,Na,Na,"1'x1'x3'4""",Na,0,,6,6,,Goa Warehouse,Zone I,Ok,,Ok,,"NaChipboard pedestal1'x1'x3'4""",,,,,,,,,,,,,,,,
Na,Production,Display,White Table with Shelf,Na,Na,"11'9""x1'6""x2'10""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaWhite Table with Shelf11'9""x1'6""x2'10""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,Black pedestal with Storage 11,Na,Na,"1'6""x1'6""x3'3""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaBlack pedestal with Storage 111'6""x1'6""x3'3""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,Grey pedestal 1,Na,Na,"1'2""x1'2""x5'2""",Na,0,,3,3,,Goa Warehouse,Zone A,Ok,,Ok,,"NaGrey pedestal 11'2""x1'2""x5'2""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,Grey pedestal 2,Na,Na,"1'6""x1'6""x5'11""",Na,0,,1,1,,Goa Warehouse,,,,,,"NaGrey pedestal 21'6""x1'6""x5'11""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,Grey pedestal 3,Na,Na,"1'6""x1'6""x7'5""",Na,0,,1,1,,Goa Warehouse,,,,,,"NaGrey pedestal 31'6""x1'6""x7'5""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,Brown pedestal 1,Na,Na,"1'6""x1'6""x2'",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaBrown pedestal 11'6""x1'6""x2'",,,,,,,,,,,,,,,,
Na,Production,Pedestal,Brown pedestal 2,Na,Na,"1'5""x1'5""x2'",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaBrown pedestal 21'5""x1'5""x2'",,,,,,,,,,,,,,,,
Na,Production,Pedestal,Brown pedestal 3,Na,Na,"3'x2'x3'6""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaBrown pedestal 33'x2'x3'6""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,Brown pedestal 4,Na,Na,1'x1'x4',Na,0,,6,6,,Goa Warehouse,Zone A,Ok,,Ok,,NaBrown pedestal 41'x1'x4',,,,,,,,,,,,,,,,
Na,Production,Cover,HS8S woofer cover,Na,Na,"1'5""x1'7x1'7""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaHS8S woofer cover1'5""x1'7x1'7""",,,,,,,,,,,,,,,,
Na,Production,Dropbox,Blue Dropbox,Na,Na,"1'3""x1'3""x3'",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaBlue Dropbox1'3""x1'3""x3'",,,,,,,,,,,,,,,,
Na,Production,Dropbox,White Dropbox,Na,Na,"1'6""x1'4""x2'3""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaWhite Dropbox1'6""x1'4""x2'3""",,,,,,,,,,,,,,,,
Na,Production,Steps,Brown steps,Na,Na,"4'5""x8""x8""",Na,0,,7,7,,Goa Warehouse,Zone A,Ok,,Ok,,"NaBrown steps4'5""x8""x8""",,,,,,,,,,,,,,,,
Na,Production,Misc.,White Bench/Pedestal,Na,Na,"3'x1'5""x1'5""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Ok,,"NaWhite Bench/Pedestal3'x1'5""x1'5""",,,,,,,,,,,,,,,,
Na,Technical,Appliance,Chest Freezer,Lloyd,LHT250,2.8'X2'X3',RIICG30700351,0,,1,1,,Goa Warehouse,Zone G,Ok,,Visual checks,,NaChest Freezer2.8'X2'X3',,,,,,,,,,,,,,,,
Na,Technical,Appliance,Chest Freezer,Lloyd,LHT250,2.8'X2'X3',RIICG30700012,0,,1,1,,Goa Warehouse,Zone G,Ok,,Visual checks,,NaChest Freezer2.8'X2'X3',,,,,,,,,,,,,,,,
Na,Technical,Appliance,Chest Freezer,Lloyd,LHT250,2.8'X2'X3',RIICG30700357,0,,1,1,,Goa Warehouse,Zone G,Ok,,Visual checks,,NaChest Freezer2.8'X2'X3',,,,,,,,,,,,,,,,
Na,Technical,Appliance,Chest Freezer,Lloyd,LHT250,2.8'X2'X3',RIICG30700307,0,,1,1,,Goa Warehouse,Zone G,Ok,,Visual checks,,NaChest Freezer2.8'X2'X3',,,,,,,,,,,,,,,,
Na,Technical,Appliance,Chest Freezer,Lloyd,LHT250,2.8'X2'X3',RIICG30700015,0,,1,1,,Goa Warehouse,Zone G,Ok,,Visual checks,,NaChest Freezer2.8'X2'X3',,,,,,,,,,,,,,,,
Na,Technical,Appliance,Chest Freezer,Lloyd,LHT250,2.8'X2'X3',RIICG30700179,0,,1,1,,Goa Warehouse,Zone G,Ok,,Visual checks,,NaChest Freezer2.8'X2'X3',,,,,,,,,,,,,,,,
Na,Technical,Appliance,Chest Freezer,Lloyd,LHT250,2.8'X2'X3',RIICG30700011,0,,1,1,,Goa Warehouse,Zone G,Ok,,Visual checks,,NaChest Freezer2.8'X2'X3',,,,,,,,,,,,,,,,
Na,Technical,Appliance,Chest Freezer,Lloyd,LHT250,2.8'X2'X3',RIICG30700186,0,,1,1,,Goa Warehouse,Zone G,Ok,,Visual checks,,NaChest Freezer2.8'X2'X3',,,,,,,,,,,,,,,,
Na,Technical,Appliance,Chest Freezer,Lloyd,LHT250,2.8'X2'X3',RIICG30700034,0,,1,1,,Goa Warehouse,Zone G,Ok,,Visual checks,,NaChest Freezer2.8'X2'X3',,,,,,,,,,,,,,,,
Na,Technical,Appliance,Chest Freezer,Lloyd,LHT250,2.8'X2'X3',RIICG30700180,0,,1,1,,Goa Warehouse,Zone G,Ok,,Visual checks,,NaChest Freezer2.8'X2'X3',,,,,,,,,,,,,,,,
Na,Technical,Appliance,Chest Freezer,Lloyd,LHT250,2.8'X2'X3',RIICG30700172,0,,1,1,,Goa Warehouse,Zone G,Ok,,Visual checks,,NaChest Freezer2.8'X2'X3',,,,,,,,,,,,,,,,
Na,Production,Table,L Table,Na,Na,5.1'X4.1X2.5',Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,NaL Table5.1'X4.1X2.5',,,,,,,,,,,,,,,,
Na,Furniture,Stool,Kyrre Stool,Na,Na,"14""x14""x18""",Na,0,,6,6,,Delhi Warehouse,To be defined,Ok,,,,"NaKyrre Stool14""x14""x18""",,,,,,,,,,,,,,,,
Na,Furniture,Chair,Dinning Wooden Chair,Na,Na,"17""x16""x37""",Na,0,,2,2,,Delhi Warehouse,To be defined,Ok,,,,"NaDinning Wooden Chair17""x16""x37""",,,,,,,,,,,,,,,,
Na,Furniture,Table,Wooden Planter Table,Na,Na,"16""x16x20""",Na,0,,1,1,,Delhi Warehouse,To be defined,Ok,,,,"NaWooden Planter Table16""x16x20""",,,,,,,,,,,,,,,,
Na,Furniture,Table,White Plastic Foldable Table,Na,Na,"60""x28""x29""",Na,0,,6,6,,Delhi Warehouse,To be defined,Ok,,,,"NaWhite Plastic Foldable Table60""x28""x29""",,,,,,,,,,,,,,,,
Na,Furniture,Board,BlackBoard,Na,Na,"48""x36""",Na,0,,2,2,,Delhi Warehouse,To be defined,Ok,,,,"NaBlackBoard48""x36""",,,,,,,,,,,,,,,,
Na,Furniture,Stool,Stool Pickle Shop 2024,Na,Na,"14""x12""x21""",Na,0,,8,8,,Delhi Warehouse,To be defined,Ok,,,,"NaStool Pickle Shop 202414""x12""x21""",,,,,,,,,,,,,,,,
Na,Furniture,Stool,Stool Shahi Tukda,Na,Na,"12""x12""x13""",Na,0,,1,1,,Delhi Warehouse,To be defined,Ok,,,,"NaStool Shahi Tukda12""x12""x13""",,,,,,,,,,,,,,,,
Na,Furniture,Table,Picnic Table,Na,Na,"48""x24""x20""",Na,0,,5,5,,Delhi Warehouse,To be defined,Ok,,,,"NaPicnic Table48""x24""x20""",,,,,,,,,,,,,,,,
Na,Furniture,Table,Panjim Market Table,Na,Na,"35""x24""x30""",Na,0,,9,9,,Delhi Warehouse,To be defined,Ok,,,,"NaPanjim Market Table35""x24""x30""",,,,,,,,,,,,,,,,
Na,Furniture,Table,Table Pickle Shop 2024,Na,Na,"47""x31""x29""",Na,0,,1,1,,Delhi Warehouse,To be defined,Ok,,,,"NaTable Pickle Shop 202447""x31""x29""",,,,,,,,,,,,,,,,
Na,Furniture,Table,Wooden Dinning Table,Na,Na,"34""x34""x30""",Na,0,,1,1,,Delhi Warehouse,To be defined,Ok,,,,"NaWooden Dinning Table34""x34""x30""",,,,,,,,,,,,,,,,
Na,Furniture,Chair,Black Cushioned Chair Conference,Na,Na,"18""x18""x30""",Na,0,,24,24,,Delhi Warehouse,To be defined,Ok,,,,"NaBlack Cushioned Chair Conference18""x18""x30""",,,,,,,,,,,,,,,,
Na,Furniture,Bench,Wooden Bench Big 6,Na,Na,"39""x12""x16""",Na,0,,7,7,,Delhi Warehouse,To be defined,Ok,,,,"NaWooden Bench Big 639""x12""x16""",,,,,,,,,,,,,,,,
Na,Furniture,Stool,Cushioned Stool,Na,Na,"18""x13""x20""",Na,0,,2,2,,Delhi Warehouse,To be defined,Ok,,,,"NaCushioned Stool18""x13""x20""",,,,,,,,,,,,,,,,
Na,Furniture,Side Table,SKM Lounge 2024,Na,Na,Na,Na,0,,1,1,,Delhi Warehouse,To be defined,Ok,,,,NaSKM Lounge 2024Na,,,,,,,,,,,,,,,,
Na,Furniture,Stool,Foldable Plastic Stool,Na,Na,"15""x13""x18""",Na,0,,6,6,,Delhi Warehouse,To be defined,Ok,,,,"NaFoldable Plastic Stool15""x13""x18""",,,,,,,,,,,,,,,,
Na,Furniture,Stool,Stool 1,Na,Na,1'X1'X1.5',Na,0,,3,3,,Goa Warehouse,Zone A,Ok,,Visual checks,,NaStool 11'X1'X1.5',,,,,,,,,,,,,,,,
Na,Furniture,Stool,Stool 2,Na,Na,"2'x2'x3'8""",Na,0,,2,2,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaStool 22'x2'x3'8""",,,,,,,,,,,,,,,,
Na,Furniture,Stool,Stool 3,Na,Na,"2'x2'x2'8""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaStool 32'x2'x2'8""",,,,,,,,,,,,,,,,
Na,Furniture,Stool,Stool 4,Na,Na,2'x2'x3',Na,0,,2,2,,Goa Warehouse,Zone A,Ok,,Visual checks,,NaStool 42'x2'x3',,,,,,,,,,,,,,,,
Na,Furniture,Stool,Stool 5,Na,Na,"1'9""x2'x2'4""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaStool 51'9""x2'x2'4""",,,,,,,,,,,,,,,,
Na,Furniture,Stool,Stool 6,Na,Na,"2'6""x1'5""x1'8""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaStool 62'6""x1'5""x1'8""",,,,,,,,,,,,,,,,
Na,Furniture,Stool,Stool 7,Na,Na,"1'x1'x1'2""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaStool 71'x1'x1'2""",,,,,,,,,,,,,,,,
Na,Furniture,Stool,Stool 9,Na,Na,"2'x2'x2'6""",Na,0,,2,2,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaStool 92'x2'x2'6""",,,,,,,,,,,,,,,,
Na,Furniture,Stool,High Stool 1,Na,Na,"1'7""x1'x2'8""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaHigh Stool 11'7""x1'x2'8""",,,,,,,,,,,,,,,,
Na,Furniture,Stool,High Stool 2,Na,Na,"1'5""x1'5""x3'",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaHigh Stool 21'5""x1'5""x3'",,,,,,,,,,,,,,,,
Na,Furniture,Stool,High Stool 3,Na,Na,1'x1'x3',Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,NaHigh Stool 31'x1'x3',,,,,,,,,,,,,,,,
Na,Furniture,Stool,High Stool 5,Na,Na,"1'5""x2'x4'3""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaHigh Stool 51'5""x2'x4'3""",,,,,,,,,,,,,,,,
Na,Furniture,Stool,High Stool 6,Na,Na,"1'3""x1'3""x2'3""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaHigh Stool 61'3""x1'3""x2'3""",,,,,,,,,,,,,,,,
Na,Furniture,Stool,High Stool 7,Na,Na,"1'3""x1'3""x2'11""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaHigh Stool 71'3""x1'3""x2'11""",,,,,,,,,,,,,,,,
Na,Furniture,Stool,Stool Blue,Na,Na,"1'2""x1'2""x2'",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaStool Blue1'2""x1'2""x2'",,,,,,,,,,,,,,,,
Na,Furniture,Stool,Stool white 1,Na,Na,"1'5""x2'",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaStool white 11'5""x2'",,,,,,,,,,,,,,,,
Na,Furniture,Stool,Stool white 2,Na,Na,"1'5""x1'6""",Na,0,,2,2,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaStool white 21'5""x1'6""",,,,,,,,,,,,,,,,
Na,Furniture,Stool,Stool Brown,Na,Na,1'x1'x3',Na,0,,2,2,,Goa Warehouse,Zone A,Ok,,Visual checks,,NaStool Brown1'x1'x3',,,,,,,,,,,,,,,,
Na,Furniture,Chair,Refree Chair,Na,Na,2'x2'x6',Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,NaRefree Chair2'x2'x6',,,,,,,,,,,,,,,,
Na,Furniture,Misc.,Water Tank,Syntax,Na,1000,Na,0,,1,1,,Goa Warehouse,Zone E,Ok,,Visual checks,,NaWater Tank1000,,,,,,,,,,,,,,,,
Na,Furniture,Misc.,Half Mannequinn - Male,Na,Na,Na,Na,0,,1,1,,Goa Warehouse,Zone E,Ok,,Visual checks,,NaHalf Mannequinn - MaleNa,,,,,,,,,,,,,,,,
Na,Furniture,Misc.,Half Mannequinn - Female,Na,Na,Na,Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,NaHalf Mannequinn - FemaleNa,,,,,,,,,,,,,,,,
Na,Furniture,Table,Table White,Na,Na,"3'x1'5""x1'8""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaTable White3'x1'5""x1'8""",,,,,,,,,,,,,,,,
Na,Furniture,Table,Table White,Na,Na,"4'x2'x2'10""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaTable White4'x2'x2'10""",,,,,,,,,,,,,,,,
Na,Furniture,Table,Table White,Na,Na,"4'6""x2'x2'6""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaTable White4'6""x2'x2'6""",,,,,,,,,,,,,,,,
Na,Furniture,Stool,Stool with white legs 1,Na,Na,"1'2""x1'2""x3'2""",Na,0,,8,8,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaStool with white legs 11'2""x1'2""x3'2""",,,,,,,,,,,,,,,,
Na,Furniture,Stool,Stool with white legs 2,Na,Na,"2'x2'x1'8""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaStool with white legs 22'x2'x1'8""",,,,,,,,,,,,,,,,
Na,Production,Display,AKFD shelves,Na,Na,"4'X6""(d)X5.9'",Na,0,,4,4,,Goa Warehouse,Zone A,Not Ok,,Need to refurbish,,"NaAKFD shelves4'X6""(d)X5.9'",,,,,,,,,,,,,,,,
Na,Production,Storage,Shelves,Na,Na,3.9'X1.2'X5.9',Na,0,,1,1,,Defence Colony,Zone A,Ok,,Visual checks,,NaShelves3.9'X1.2'X5.9',,,,,,,,,,,,,,,,
Na,Furniture,Bench,Bench with black legs,Na,Na,"7'x3'x1'8""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaBench with black legs7'x3'x1'8""",,,,,,,,,,,,,,,,
Na,Furniture,Bench,Bench with black legs,Na,Na,"6'x1'6""x1'6""",Na,0,,2,2,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaBench with black legs6'x1'6""x1'6""",,,,,,,,,,,,,,,,
Na,Furniture,Bench,Bench with black legs,Na,Na,"4'x1'5""x1'6""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaBench with black legs4'x1'5""x1'6""",,,,,,,,,,,,,,,,
Na,Furniture,Bench,Bench with black legs,Na,Na,"4'x1'5""x1'6""",Na,0,,15,15,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaBench with black legs4'x1'5""x1'6""",,,,,,,,,,,,,,,,
Na,Furniture,Bench,Bench with black legs,Na,Na,"6'x1'6""x1'6""",Na,0,,4,4,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaBench with black legs6'x1'6""x1'6""",,,,,,,,,,,,,,,,
Na,Furniture,Bench,Bench with black legs,Na,Na,"7'x1'6""x1'7""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks|Black Painted,,"NaBench with black legs7'x1'6""x1'7""",,,,,,,,,,,,,,,,
Na,Furniture,Bench,Bench with black legs,Na,Na,"10'x1'6""x1'9""",Na,0,,2,2,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaBench with black legs10'x1'6""x1'9""",,,,,,,,,,,,,,,,
Na,Furniture,Bench,Bench with black legs,Na,Na,"6'x1'6""x1'8""",Na,0,,3,3,,Goa Warehouse,Zone A,Ok,,Visual checks| 1 Black Painted,,"NaBench with black legs6'x1'6""x1'8""",,,,,,,,,,,,,,,,
Na,Furniture,Bench,Bench with black legs,Na,Na,"8'x1'5""x1'8""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaBench with black legs8'x1'5""x1'8""",,,,,,,,,,,,,,,,
Na,Furniture,Bench,Bench with black legs,Na,Na,"3'6""x1'6""x1'8""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaBench with black legs3'6""x1'6""x1'8""",,,,,,,,,,,,,,,,
Na,Furniture,Table,High Table,Na,Na,4'x2'x3',Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,NaHigh Table4'x2'x3',,,,,,,,,,,,,,,,
Na,Furniture,Table,High Table,Na,Na,"1'8""x1'8""x3'",Na,0,,3,3,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaHigh Table1'8""x1'8""x3'",,,,,,,,,,,,,,,,
Na,Furniture,Table,High Table beige color with white legs,Na,Na,"3'x1'6""x2'9""",Na,0,,3,3,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaHigh Table beige color with white legs3'x1'6""x2'9""",,,,,,,,,,,,,,,,
Na,Furniture,Table,High Table beige color with white legs,Na,Na,"3'x1'7""x2'7""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaHigh Table beige color with white legs3'x1'7""x2'7""",,,,,,,,,,,,,,,,
Na,Furniture,Table,High Table beige color with white legs,Na,Na,"4'x2'x2'7""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaHigh Table beige color with white legs4'x2'x2'7""",,,,,,,,,,,,,,,,
Na,Furniture,Table,High Table beige color with white legs,Na,Na,"4'x2'3""x2'7""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaHigh Table beige color with white legs4'x2'3""x2'7""",,,,,,,,,,,,,,,,
Na,Furniture,Table,High Table beige color with white legs,Na,Na,"3'10""x1'5""x3'2""",Na,0,,2,2,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaHigh Table beige color with white legs3'10""x1'5""x3'2""",,,,,,,,,,,,,,,,
Na,Furniture,Table,High Table beige color with white legs,Na,Na,"2'x1'x2'2""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaHigh Table beige color with white legs2'x1'x2'2""",,,,,,,,,,,,,,,,
Na,Furniture,Table,High Table beige color with white legs,Na,Na,"4'4""x1'10""x2'8""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaHigh Table beige color with white legs4'4""x1'10""x2'8""",,,,,,,,,,,,,,,,
Na,Furniture,Table,High Table beige color with white legs,Na,Na,"3'x1'6""x2'10""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaHigh Table beige color with white legs3'x1'6""x2'10""",,,,,,,,,,,,,,,,
Na,Furniture,Table,Table,Na,Na,"5'x2'x2'6""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaTable5'x2'x2'6""",,,,,,,,,,,,,,,,
Na,Furniture,Table,Table,Na,Na,"6'x2'x2'6""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaTable6'x2'x2'6""",,,,,,,,,,,,,,,,
Na,Furniture,Table,Table,Na,Na,"5'x2'x2'9""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaTable5'x2'x2'9""",,,,,,,,,,,,,,,,
Na,Furniture,Table,Table,Na,Na,"5'x2'x3'6""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaTable5'x2'x3'6""",,,,,,,,,,,,,,,,
Na,Furniture,Table,Display Table,Na,Na,"4'x1'3""x2'",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaDisplay Table4'x1'3""x2'",,,,,,,,,,,,,,,,
Na,Furniture,Table,Table Beige with White legs,Na,Na,"3'x2'x2'2""",Na,0,,6,6,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaTable Beige with White legs3'x2'x2'2""",,,,,,,,,,,,,,,,
Na,Furniture,Table,Table Beige with White legs,Na,Na,"3'x1'6""x2'9""",Na,0,,5,5,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaTable Beige with White legs3'x1'6""x2'9""",,,,,,,,,,,,,,,,
Na,Furniture,Bench,Bench,Na,Na,"6'6""x2'6""x1'",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaBench6'6""x2'6""x1'",,,,,,,,,,,,,,,,
Na,Furniture,Bench,Bench,Na,Na,"4'4""x2'4""x1'",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaBench4'4""x2'4""x1'",,,,,,,,,,,,,,,,
Na,Furniture,Bench,Chipboard Bench,Na,Na,"4'x2'x1'7""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaChipboard Bench4'x2'x1'7""",,,,,,,,,,,,,,,,
Na,Furniture,Bench,Chipboard Bench,Na,Na,3'x1'x2',Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,in camera room,,NaChipboard Bench3'x1'x2',,,,,,,,,,,,,,,,
Na,Furniture,Bench,Bench Beige with white legs,Na,Na,"4'x1'x1'5""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaBench Beige with white legs4'x1'x1'5""",,,,,,,,,,,,,,,,
Na,Furniture,Bench,Bench Beige with white legs,Na,Na,"3'x1'x1'7""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaBench Beige with white legs3'x1'x1'7""",,,,,,,,,,,,,,,,
Na,Furniture,Table,Black Extendable Table,Na,Na,"4'x2'6""x2""5'",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaBlack Extendable Table4'x2'6""x2""5'",,,,,,,,,,,,,,,,
Na,Furniture,Table,Table - Mango Wood/Damaged,Na,Na,"5'x2'x2'6""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaTable - Mango Wood/Damaged5'x2'x2'6""",,,,,,,,,,,,,,,,
Na,Furniture,Chair,Black Foldable Chairs,Na,Na,Na,Na,0,,264,264,,Goa Warehouse,Zone H,Ok,,Visual checks,,NaBlack Foldable ChairsNa,,,,,,,,,,,,,,,,
Na,Production,Pedestal,Customized pedestal,Na,Na,"1'4""x1'4""x4'7""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaCustomized pedestal1'4""x1'4""x4'7""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,Customized pedestal,Na,Na,"1'6""x1'6""x4'7""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaCustomized pedestal1'6""x1'6""x4'7""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,Customized pedestal,Na,Na,1'x1'x4',Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,NaCustomized pedestal1'x1'x4',,,,,,,,,,,,,,,,
Na,Production,Pedestal,Customized pedestal,Na,Na,"1'6""x1'6""x4'5""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaCustomized pedestal1'6""x1'6""x4'5""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,Customized pedestal,Na,Na,"1'2""x1'2""x4'4""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaCustomized pedestal1'2""x1'2""x4'4""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,Customized pedestal,Na,Na,"1'x1'x3'10""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaCustomized pedestal1'x1'x3'10""",,,,,,,,,,,,,,,,
Na,Production,Pedestal,Customized pedestal,Na,Na,"1'x1'x4'4""",Na,0,,2,2,,Goa Warehouse,Zone A,Ok,,Visual checks,,"NaCustomized pedestal1'x1'x4'4""",,,,,,,,,,,,,,,,
Na,Production,Accessability,Wheel Chair,Na,Na,Na,Na,0,,13,13,,Goa Warehouse,Zone B,Bad,,Bad Seats & Mechanism,,NaWheel ChairNa,,,,,,,,,,,,,,,,
Na,Production,Misc.,Mirror black frame,Na,Na,4'x6',Na,0,,1,1,,Goa Warehouse,Zone G,Ok,,Na,,NaMirror black frame4'x6',,,,,,,,,,,,,,,,
Na,Production,Misc.,Black Rectangular metal pipes,Na,Na,4',Na,0,,9,9,,Goa Warehouse,Zone G,Ok,,Used for projector mounting,,NaBlack Rectangular metal pipes4',,,,,,,,,,,,,,,,
Na,Production,Misc.,Black L shaped metal pipes,Na,Na,4',Na,0,,1,1,,Goa Warehouse,Zone G,Ok,,Used for projector mounting,,NaBlack L shaped metal pipes4',,,,,,,,,,,,,,,,
Na,Production,Misc.,Black L shaped metal pipes,Na,Na,"2'6""",Na,0,,2,2,,Goa Warehouse,Zone G,Ok,,Used for projector mounting,,"NaBlack L shaped metal pipes2'6""",,,,,,,,,,,,,,,,
Na,Production,Misc.,Black Support metal pipes,Na,Na,"1'1""",Na,0,,33,33,,Goa Warehouse,Zone G,Ok,,Used for projector mounting,,"NaBlack Support metal pipes1'1""",,,,,,,,,,,,,,,,
Na,Production,Misc.,Clear Shed,Na,Na,"8'x3'4""",Na,0,,3,3,,Goa Warehouse,Zone A,Ok,,Used for projector mounting,,"NaClear Shed8'x3'4""",,,,,,,,,,,,,,,,
Na,Production,Misc.,Shop Display Shelf,Na,Na,"8'x2'x8'8""",Na,0,,2,2,,Goa Warehouse,Zone B,Ok,,Used for projector mounting,,"NaShop Display Shelf8'x2'x8'8""",,,,,,,,,,,,,,,,
Na,Production,Misc.,Metal Mesh,Na,Na,14'X3',Na,0,,5,5,,Goa Warehouse,Zone A,Ok,,,,NaMetal Mesh14'X3',,,,,,,,,,,,,,,,
Na,Production,Panels,Panels with Cavity for display,Na,Na,"7'9"" x1'x6'7""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,,,"NaPanels with Cavity for display7'9"" x1'x6'7""",,,,,,,,,,,,,,,,
Na,Production,Panels,Panels with Cavity for display,Na,Na,"7'9""x 1'x8'6""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,,,"NaPanels with Cavity for display7'9""x 1'x8'6""",,,,,,,,,,,,,,,,
Na,Production,Panels,Panels with Cavity for display,Na,Na,"7'7""X10""x7'10""",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,,,"NaPanels with Cavity for display7'7""X10""x7'10""",,,,,,,,,,,,,,,,
Na,Furniture,Table,Food Lab Table,Na,Na,10'x1'x3',Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Refurbishment required,,NaFood Lab Table10'x1'x3',,,,,,,,,,,,,,,,
Na,Furniture,Table,Food Lab Table,Na,Na,"15'x1'7""x2'9""",Na,0,,5,5,,Goa Warehouse,Zone A,Ok,,Refurbishment required,,"NaFood Lab Table15'x1'7""x2'9""",,,,,,,,,,,,,,,,
Na,Furniture,Table,Food Lab Table,Na,Na,8'x4'x3',Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Refurbishment required,,NaFood Lab Table8'x4'x3',,,,,,,,,,,,,,,,
Na,Production,Misc.,Clothes Rack,Na,Na,Standard,Na,0,,9,9,,Goa Warehouse,Zone D,Ok,,Na,,NaClothes RackStandard,,,,,,,,,,,,,,,,
Na,Furniture,Chair,White chairs,Ikea,Na,Standard,Na,0,,48,48,,Goa Warehouse,Zone H,Ok,,Na,,NaWhite chairsStandard,,,,,,,,,,,,,,,,
Na,Furniture,Chair,White Stools,Ikea,Na,Standard,Na,0,,34,34,,Goa Warehouse,Zone H,Ok,,Na,,NaWhite StoolsStandard,,,,,,,,,,,,,,,,
Na,Furniture,Chair,Bamboo Foldable Chair,Local,Na,Standard,Na,0,,5,5,,Goa Warehouse,Zone A,Ok,,Na,,NaBamboo Foldable ChairStandard,,,,,,,,,,,,,,,,
Na,Furniture,Chair,Ghost Chair,Na,Na,Na,Na,0,,1,1,,Goa Warehouse,Zone H,Ok,,Na,,NaGhost ChairNa,,,,,,,,,,,,,,,,
Na,Furniture,Chair,White Poufs buttoned,Na,Na,"1'x1'x1'3""",Na,0,,1,1,,Goa Warehouse,Zone I,Ok,,Na,,"NaWhite Poufs buttoned1'x1'x1'3""",,,,,,,,,,,,,,,,
Na,Furniture,Table,T table/Damaged,Na,Na,"4'7"" x2'7""x2'7""",Na,0,,1,1,,Goa Warehouse,Zone E,Ok,,Na,,"NaT table/Damaged4'7"" x2'7""x2'7""",,,,,,,,,,,,,,,,
Na,Production,Misc.,Black Boards,Na,Na,2'X3',Na,0,,7,7,,Goa Warehouse,Zone D,Ok,,Na,,NaBlack Boards2'X3',,,,,,,,,,,,,,,,
Na,Production,Misc.,Text Matter Boards,Na,Na,"4'8""X1'7""X8",Na,0,,5,5,,Goa Warehouse,Zone F,Ok,,Na,,"NaText Matter Boards4'8""X1'7""X8",,,,,,,,,,,,,,,,
Na,Production,Display,Shelf White 1,Na,Na,"6'x1'2""5'10""",Na,0,,3,3,,Goa Warehouse,Zone F,Ok,,Damaged,,"NaShelf White 16'x1'2""5'10""",,,,,,,,,,,,,,,,
Na,Production,Display,Shelf White 2,Na,Na,"3'x1'5""x6""",Na,0,,1,1,,Goa Warehouse,Zone F,Ok,,Na,,"NaShelf White 23'x1'5""x6""",,,,,,,,,,,,,,,,
Na,Production,Display,Shelf White,Na,Na,"4'x1'x3""",Na,0,,1,1,,Goa Warehouse,Zone F,Ok,,Na,,"NaShelf White4'x1'x3""",,,,,,,,,,,,,,,,
Na,Production,Display,Shelf Brown,Na,Na,"2'x1'6""x1'",Na,0,,1,1,,Goa Warehouse,Zone F,Ok,,Na,,"NaShelf Brown2'x1'6""x1'",,,,,,,,,,,,,,,,
Na,Production,Display,Shelf Black,Na,Na,"1'3""x1'2""x10""",Na,0,,1,1,,Goa Warehouse,Zone F,Ok,,Na,,"NaShelf Black1'3""x1'2""x10""",,,,,,,,,,,,,,,,
Na,Production,Display,Book Shelf Bookworm,Na,Na,3' x1'x5',Na,0,,4,4,,Goa Warehouse,Zone F,Ok,,Na,,NaBook Shelf Bookworm3' x1'x5',,,,,,,,,,,,,,,,
Na,Production,Display,Mercad Shelf,Na,Na,2'x1'x7',Na,0,,29,29,,Goa Warehouse,Zone F,Ok,,Na,,NaMercad Shelf2'x1'x7',,,,,,,,,,,,,,,,
Na,Production,Display,Suggestion Box,Na,Na,"1'5""x1'5""x1'5""",Na,0,,1,1,,Goa Warehouse,Zone F,Ok,,Na,,"NaSuggestion Box1'5""x1'5""x1'5""",,,,,,,,,,,,,,,,
Na,Production,Display,Chipboard High Table,Na,Na,5'x1'x3',Na,0,,1,1,,Goa Warehouse,Zone F,Ok,,Na,,NaChipboard High Table5'x1'x3',,,,,,,,,,,,,,,,
Na,Production,Display,Brown Vitrine,Na,Na,"2'6""2'8""x4'",Na,0,,1,1,,Delhi Warehouse,Zone A,Ok,,Na,,"NaBrown Vitrine2'6""2'8""x4'",,,,,,,,,,,,,,,,
Na,Production,Display,Brown Vitrine,Na,Na,"4'x2'x3'10""",Na,0,,1,1,,Delhi Warehouse,Zone A,Ok,,Na,,"NaBrown Vitrine4'x2'x3'10""",,,,,,,,,,,,,,,,
Na,Production,Display,White Vitrine 1,Na,Na,"3 'x2'x2'6""",Na,0,,4,4,,Goa Warehouse,Zone A,Ok,,Na,,"NaWhite Vitrine 13 'x2'x2'6""",,,,,,,,,,,,,,,,
Na,Production,Display,White Vitrine (light Box) 2,Na,Na,"8' x2'8""x3'",Na,0,,1,1,,Goa Warehouse,Zone C,Ok,,Na,,"NaWhite Vitrine (light Box) 28' x2'8""x3'",,,,,,,,,,,,,,,,
Na,Production,Display,White Vitrine (light Box) 3,Na,Na,"5'11""x3'x2'10""",Na,0,,2,2,,Goa Warehouse,Zone C,Ok,,Na,,"NaWhite Vitrine (light Box) 35'11""x3'x2'10""",,,,,,,,,,,,,,,,
Na,Production,Display,White Vitrine (light Box) - without legs 4,Na,Na,"6'4""x1'6""x6""",Na,0,,1,1,,Goa Warehouse,Zone C,Ok,,Na,,"NaWhite Vitrine (light Box) - without legs 46'4""x1'6""x6""",,,,,,,,,,,,,,,,
Na,Production,Display,White Vitrine (light Box) - without legs 5,Na,Na,"5'x1'6""x5""",Na,0,,1,1,,Goa Warehouse,Zone C,Ok,,Na,,"NaWhite Vitrine (light Box) - without legs 55'x1'6""x5""",,,,,,,,,,,,,,,,
Na,Production,Display,White Vitrine (light Box) 6,Na,Na,"6'x1'2""x4""",Na,0,,1,1,,Goa Warehouse,Zone C,Ok,,Na,,"NaWhite Vitrine (light Box) 66'x1'2""x4""",,,,,,,,,,,,,,,,
Na,Production,Display,White Vitrine (light Box) 7,Na,Na,"5'x1'6""x5""",Na,0,,4,4,,Goa Warehouse,Zone C,Ok,,Na,,"NaWhite Vitrine (light Box) 75'x1'6""x5""",,,,,,,,,,,,,,,,
Na,Production,Display,White Vitrine (light Box) 8,Na,Na,"7'x2'x5""",Na,0,,1,1,,Goa Warehouse,Zone C,Ok,,Na,,"NaWhite Vitrine (light Box) 87'x2'x5""",,,,,,,,,,,,,,,,
Na,Production,Display,White Vitrine (light BoX),Na,Na,"13'5""x3'x2'2""",Na,0,,1,1,,Goa Warehouse,Zone C,Ok,,Na,,"NaWhite Vitrine (light BoX)13'5""x3'x2'2""",,,,,,,,,,,,,,,,
Na,Production,Display,Green Vitrine (light Box),Na,Na,"5'9""x1'3""x4""",Na,0,,1,1,,Goa Warehouse,Zone F,Ok,,Na,,"NaGreen Vitrine (light Box)5'9""x1'3""x4""",,,,,,,,,,,,,,,,
Na,Production,Display,Green curved table,Na,Na,6'x2'x3',Na,0,,1,1,,Goa Warehouse,Zone G,Ok,,Na,,NaGreen curved table6'x2'x3',,,,,,,,,,,,,,,,
Na,Production,Display,Brown table/not repairble,Na,Na,"3'3""x1'9""x3'",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Na,,"NaBrown table/not repairble3'3""x1'9""x3'",,,,,,,,,,,,,,,,
Na,Production,Frame,Black Iron Frame,Na,Na,"1'9""x2'7""x6'4""",Na,0,,1,1,,Goa Warehouse,Zone C,Ok,,Na,,"NaBlack Iron Frame1'9""x2'7""x6'4""",,,,,,,,,,,,,,,,
Na,Production,Frame,White Iron Frame,Na,Na,Na,Na,0,,10,10,,Goa Warehouse,Zone C,Ok,,Na,,NaWhite Iron FrameNa,,,,,,,,,,,,,,,,
Na,Production,Frame,White Iron Frame,Na,Na,"2'x1'8""x2'4""",Na,0,,1,1,,Goa Warehouse,Zone C,Ok,,Na,,"NaWhite Iron Frame2'x1'8""x2'4""",,,,,,,,,,,,,,,,
Na,Production,Frame,A Stands Metal,Na,Na,"3'x2'x4'10""",Na,0,,30,30,,Goa Warehouse,Zone C,Ok,,Na,,"NaA Stands Metal3'x2'x4'10""",,,,,,,,,,,,,,,,
Na,Production,Frame,Black Stands,Na,Na,"2'x2'x5'4""",Na,0,,2,2,,Goa Warehouse,Zone A,Ok,,Na,,"NaBlack Stands2'x2'x5'4""",,,,,,,,,,,,,,,,
Na,Production,Frame,Grey Iron Frames,Na,Na,"2'x1'6""x3'",Na,0,,8,8,,Goa Warehouse,Zone A,Ok,,Na,,"NaGrey Iron Frames2'x1'6""x3'",,,,,,,,,,,,,,,,
Na,Production,Frame,White Iron Frames,Na,Na,"3'10x1'5""x3'3""",Na,0,,3,3,,Goa Warehouse,Zone A,Ok,,Na,,"NaWhite Iron Frames3'10x1'5""x3'3""",,,,,,,,,,,,,,,,
Na,Production,Frame,White Iron Frames,Na,Na,"4'x1'6""x2'",Na,0,,5,5,,Goa Warehouse,Zone A,Ok,,Na,,"NaWhite Iron Frames4'x1'6""x2'",,,,,,,,,,,,,,,,
Na,Production,Stand,Black Iron Stands,Na,Na,"10""x8""x5'",Na,0,,8,8,,Goa Warehouse,Zone A,Ok,,Na,,"NaBlack Iron Stands10""x8""x5'",,,,,,,,,,,,,,,,
Na,Production,Stand,Black Iron Stands with triangular base,Na,Na,"1'x1'2""x4'7""",Na,0,,4,4,,Goa Warehouse,Zone A,Ok,,Na,,"NaBlack Iron Stands with triangular base1'x1'2""x4'7""",,,,,,,,,,,,,,,,
Na,Production,Stand,Black Iron Frames,Na,Na,"2'6""x1'x2'",Na,0,,5,5,,Goa Warehouse,Zone A,Ok,,Na,,"NaBlack Iron Frames2'6""x1'x2'",,,,,,,,,,,,,,,,
Na,Furniture,Table,Side Table,Na,Na,"1'5""x1'5""x2'3""",Na,0,,1,1,,Goa Warehouse,Zone G,Ok,,Refurbishment required,,"NaSide Table1'5""x1'5""x2'3""",,,,,,,,,,,,,,,,
Na,Production,Stand,Base for Projectors,Na,Na,Na,Na,0,,47,47,,Goa Warehouse,Zone G,Ok,,Na,,NaBase for ProjectorsNa,,,,,,,,,,,,,,,,
Na,Production,Stand,Base for Projectors with Claw,Na,Na,Na,Na,0,,47,47,,Goa Warehouse,Zone G,Ok,,Na,,NaBase for Projectors with ClawNa,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Outdoor Unit,Lloyd,GLT24B22MT,85.0 cm x 31.0 cm x 68.4 cm,87IJG03S01044,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Outdoor Unit85.0 cm x 31.0 cm x 68.4 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Outdoor Unit,Lloyd,GLT24B22MT,85.0 cm x 31.0 cm x 68.4 cm,87IJG03S01046,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Outdoor Unit85.0 cm x 31.0 cm x 68.4 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Outdoor Unit,Lloyd,GLT24B22MT,85.0 cm x 31.0 cm x 68.4 cm,87IJG03S01195,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Outdoor Unit85.0 cm x 31.0 cm x 68.4 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Outdoor Unit,Lloyd,GLT24B22MT,85.0 cm x 31.0 cm x 68.4 cm,87IJG03S00980,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Outdoor Unit85.0 cm x 31.0 cm x 68.4 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Outdoor Unit,Lloyd,GLT24B22MT,85.0 cm x 31.0 cm x 68.4 cm,87IJG03S00975,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Outdoor Unit85.0 cm x 31.0 cm x 68.4 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Outdoor Unit,Lloyd,GLT24B22MT,85.0 cm x 31.0 cm x 68.4 cm,87IJG03S00992,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Outdoor Unit85.0 cm x 31.0 cm x 68.4 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Outdoor Unit,Lloyd,GLT24B22MT,85.0 cm x 31.0 cm x 68.4 cm,87IJG03S00977,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Outdoor Unit85.0 cm x 31.0 cm x 68.4 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Outdoor Unit,Lloyd,GLT24B22MT,85.0 cm x 31.0 cm x 68.4 cm,87IJG03S00976,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Outdoor Unit85.0 cm x 31.0 cm x 68.4 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Outdoor Unit,Lloyd,GLT24B22MT,85.0 cm x 31.0 cm x 68.4 cm,87IJG03S01185,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Outdoor Unit85.0 cm x 31.0 cm x 68.4 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Outdoor Unit,Lloyd,GLT24B22MT,85.0 cm x 31.0 cm x 68.4 cm,87IJG03S01121,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Outdoor Unit85.0 cm x 31.0 cm x 68.4 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Outdoor Unit,Lloyd,GLT24B22MT,85.0 cm x 31.0 cm x 68.4 cm,87IJG03S00970,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Outdoor Unit85.0 cm x 31.0 cm x 68.4 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Outdoor Unit,Lloyd,GLT24B22MT,85.0 cm x 31.0 cm x 68.4 cm,87IJG03S01184,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Outdoor Unit85.0 cm x 31.0 cm x 68.4 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Outdoor Unit,Lloyd,GLT24B22MT,85.0 cm x 31.0 cm x 68.4 cm,87IJG03S00979,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Outdoor Unit85.0 cm x 31.0 cm x 68.4 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Outdoor Unit,Lloyd,GLT24B22MT,85.0 cm x 31.0 cm x 68.4 cm,87IJG03S00969,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Outdoor Unit85.0 cm x 31.0 cm x 68.4 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Outdoor Unit,Lloyd,GLT24B22MT,85.0 cm x 31.0 cm x 68.4 cm,87IJG03S00981,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Outdoor Unit85.0 cm x 31.0 cm x 68.4 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Outdoor Unit,Lloyd,GLT24B22MT,85.0 cm x 31.0 cm x 68.4 cm,87IJG03S00967,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Outdoor Unit85.0 cm x 31.0 cm x 68.4 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Outdoor Unit,Lloyd,GLT24B22MT,85.0 cm x 31.0 cm x 68.4 cm,87IJG03S00993,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Outdoor Unit85.0 cm x 31.0 cm x 68.4 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Outdoor Unit,Lloyd,GLT24B22MT,85.0 cm x 31.0 cm x 68.4 cm,87IJG03S00974,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Outdoor Unit85.0 cm x 31.0 cm x 68.4 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Outdoor Unit,Lloyd,GLT24B22MT,85.0 cm x 31.0 cm x 68.4 cm,87IJG03S00965,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Outdoor Unit85.0 cm x 31.0 cm x 68.4 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Outdoor Unit,Lloyd,GLT24B22MT,85.0 cm x 31.0 cm x 68.4 cm,87IJG03S01055,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Outdoor Unit85.0 cm x 31.0 cm x 68.4 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Outdoor Unit,Lloyd,GLT24B22MT,85.0 cm x 31.0 cm x 68.4 cm,87IJG03S00955,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Outdoor Unit85.0 cm x 31.0 cm x 68.4 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Outdoor Unit,Lloyd,GLT24B22MT,85.0 cm x 31.0 cm x 68.4 cm,87IJG03S00968,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Outdoor Unit85.0 cm x 31.0 cm x 68.4 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Outdoor Unit,Lloyd,GLT24B22MT,85.0 cm x 31.0 cm x 68.4 cm,87IJG03S01197,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Outdoor Unit85.0 cm x 31.0 cm x 68.4 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Outdoor Unit,Lloyd,GLT24B22MT,85.0 cm x 31.0 cm x 68.4 cm,87IJG03S00964,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Outdoor Unit85.0 cm x 31.0 cm x 68.4 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Outdoor Unit,Lloyd,GLT24B22MT,85.0 cm x 31.0 cm x 68.4 cm,87IJG03S00982,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Outdoor Unit85.0 cm x 31.0 cm x 68.4 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Outdoor Unit,Lloyd,GLT24B22MT,85.0 cm x 31.0 cm x 68.4 cm,Na,0,,1,1,,Goa Warehouse,Zone G,Ok,,Serial number sticker removed,,NaTower AC - Outdoor Unit85.0 cm x 31.0 cm x 68.4 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Outdoor Unit,Lloyd,GLT24B22MT,85.0 cm x 31.0 cm x 68.4 cm,Na,0,,1,1,,Goa Warehouse,Zone G,Ok,,Serial number sticker removed,,NaTower AC - Outdoor Unit85.0 cm x 31.0 cm x 68.4 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Outdoor Unit,Lloyd,GLT24B22MT,85.0 cm x 31.0 cm x 68.4 cm,Na,0,,1,1,,Goa Warehouse,Zone G,Ok,,Serial number sticker removed,,NaTower AC - Outdoor Unit85.0 cm x 31.0 cm x 68.4 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Outdoor Unit,Lloyd,GLT24B22MT,85.0 cm x 31.0 cm x 68.4 cm,Na,0,,1,1,,Goa Warehouse,Zone G,Ok,,Serial number sticker removed,,NaTower AC - Outdoor Unit85.0 cm x 31.0 cm x 68.4 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Outdoor Unit,Lloyd,GLT24B22MT,85.0 cm x 31.0 cm x 68.4 cm,Na,0,,1,1,,Goa Warehouse,Zone G,Ok,,Serial number sticker removed,,NaTower AC - Outdoor Unit85.0 cm x 31.0 cm x 68.4 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Indoor Unit,Lloyd,GLT24B22MT,50.6 cm x 31.5 cm x 178.0 cm,87IJG03S00323,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Indoor Unit50.6 cm x 31.5 cm x 178.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Indoor Unit,Lloyd,GLT24B22MT,50.6 cm x 31.5 cm x 178.0 cm,87IJG03S00278,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Indoor Unit50.6 cm x 31.5 cm x 178.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Indoor Unit,Lloyd,GLT24B22MT,50.6 cm x 31.5 cm x 178.0 cm,87IKG03S00027,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Indoor Unit50.6 cm x 31.5 cm x 178.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Indoor Unit,Lloyd,GLT24B22MT,50.6 cm x 31.5 cm x 178.0 cm,87IKG03S00033,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Indoor Unit50.6 cm x 31.5 cm x 178.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Indoor Unit,Lloyd,GLT24B22MT,50.6 cm x 31.5 cm x 178.0 cm,87IJG03S00279,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Indoor Unit50.6 cm x 31.5 cm x 178.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Indoor Unit,Lloyd,GLT24B22MT,50.6 cm x 31.5 cm x 178.0 cm,87IKG03S00022,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Indoor Unit50.6 cm x 31.5 cm x 178.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Indoor Unit,Lloyd,GLT24B22MT,50.6 cm x 31.5 cm x 178.0 cm,87IJG03S00445,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Indoor Unit50.6 cm x 31.5 cm x 178.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Indoor Unit,Lloyd,GLT24B22MT,50.6 cm x 31.5 cm x 178.0 cm,87IJG03S00269,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Indoor Unit50.6 cm x 31.5 cm x 178.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Indoor Unit,Lloyd,GLT24B22MT,50.6 cm x 31.5 cm x 178.0 cm,87IKG03S00023,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Indoor Unit50.6 cm x 31.5 cm x 178.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Indoor Unit,Lloyd,GLT24B22MT,50.6 cm x 31.5 cm x 178.0 cm,87IJG03S00232,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Indoor Unit50.6 cm x 31.5 cm x 178.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Indoor Unit,Lloyd,GLT24B22MT,50.6 cm x 31.5 cm x 178.0 cm,87IJG03S00525,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Indoor Unit50.6 cm x 31.5 cm x 178.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Indoor Unit,Lloyd,GLT24B22MT,50.6 cm x 31.5 cm x 178.0 cm,87IJG03S00292,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Indoor Unit50.6 cm x 31.5 cm x 178.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Indoor Unit,Lloyd,GLT24B22MT,50.6 cm x 31.5 cm x 178.0 cm,87IKG03S00031,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Indoor Unit50.6 cm x 31.5 cm x 178.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Indoor Unit,Lloyd,GLT24B22MT,50.6 cm x 31.5 cm x 178.0 cm,87IKG03S00020,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Indoor Unit50.6 cm x 31.5 cm x 178.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Indoor Unit,Lloyd,GLT24B22MT,50.6 cm x 31.5 cm x 178.0 cm,87IJG03S00329,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Indoor Unit50.6 cm x 31.5 cm x 178.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Indoor Unit,Lloyd,GLT24B22MT,50.6 cm x 31.5 cm x 178.0 cm,87IKG03S00029,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Indoor Unit50.6 cm x 31.5 cm x 178.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Indoor Unit,Lloyd,GLT24B22MT,50.6 cm x 31.5 cm x 178.0 cm,87IJG03S00319,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Indoor Unit50.6 cm x 31.5 cm x 178.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Indoor Unit,Lloyd,GLT24B22MT,50.6 cm x 31.5 cm x 178.0 cm,87IJG03S00282,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Indoor Unit50.6 cm x 31.5 cm x 178.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Indoor Unit,Lloyd,GLT24B22MT,50.6 cm x 31.5 cm x 178.0 cm,87IJG03S004373,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Indoor Unit50.6 cm x 31.5 cm x 178.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Indoor Unit,Lloyd,GLT24B22MT,50.6 cm x 31.5 cm x 178.0 cm,87IKG03S00021,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Indoor Unit50.6 cm x 31.5 cm x 178.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Indoor Unit,Lloyd,GLT24B22MT,50.6 cm x 31.5 cm x 178.0 cm,87IKG03S00025,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Indoor Unit50.6 cm x 31.5 cm x 178.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Indoor Unit,Lloyd,GLT24B22MT,50.6 cm x 31.5 cm x 178.0 cm,87IJG03S00271,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Indoor Unit50.6 cm x 31.5 cm x 178.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Indoor Unit,Lloyd,GLT24B22MT,50.6 cm x 31.5 cm x 178.0 cm,87IKG03S00019,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Indoor Unit50.6 cm x 31.5 cm x 178.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Indoor Unit,Lloyd,GLT24B22MT,50.6 cm x 31.5 cm x 178.0 cm,87IKG03S00026,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Indoor Unit50.6 cm x 31.5 cm x 178.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Indoor Unit,Lloyd,GLT24B22MT,50.6 cm x 31.5 cm x 178.0 cm,87IKG03S00028,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Indoor Unit50.6 cm x 31.5 cm x 178.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Indoor Unit,Lloyd,GLT24B22MT,50.6 cm x 31.5 cm x 178.0 cm,87IKG03S00030,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Indoor Unit50.6 cm x 31.5 cm x 178.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Indoor Unit,Lloyd,GLT24B22MT,50.6 cm x 31.5 cm x 178.0 cm,87IKG03S00032,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Indoor Unit50.6 cm x 31.5 cm x 178.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Indoor Unit,Lloyd,GLT24B22MT,50.6 cm x 31.5 cm x 178.0 cm,87IJG03S00237,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Indoor Unit50.6 cm x 31.5 cm x 178.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Indoor Unit,Lloyd,GLT24B22MT,50.6 cm x 31.5 cm x 178.0 cm,87IJG03S00321,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaTower AC - Indoor Unit50.6 cm x 31.5 cm x 178.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower AC - Indoor Unit,Lloyd,GLT24B22MT,50.6 cm x 31.5 cm x 178.0 cm,Na,0,,1,1,,Goa Warehouse,Zone G,Ok,,Serial number sticker removed,,NaTower AC - Indoor Unit50.6 cm x 31.5 cm x 178.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Split AC - Outdoor Unit,Lloyd,GLS24B32ABWA,94.0 cm x 37.0 cm x 68.0 cm,87IDG03701324,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaSplit AC - Outdoor Unit94.0 cm x 37.0 cm x 68.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Split AC - Outdoor Unit,Lloyd,GLS24B32ABWA,94.0 cm x 37.0 cm x 68.0 cm,87IGG03701498,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaSplit AC - Outdoor Unit94.0 cm x 37.0 cm x 68.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Split AC - Outdoor Unit,Lloyd,GLS24B32ABWA,94.0 cm x 37.0 cm x 68.0 cm,87IGG0370156,0,,1,1,,Goa Warehouse,Zone G,Ok,,Last digit of the SR cant be seen,,NaSplit AC - Outdoor Unit94.0 cm x 37.0 cm x 68.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Split AC - Outdoor Unit,Lloyd,GLS24B32ABWA,94.0 cm x 37.0 cm x 68.0 cm,87IGG03701563,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaSplit AC - Outdoor Unit94.0 cm x 37.0 cm x 68.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Split AC - Outdoor Unit,Lloyd,GLS24B32ABWA,94.0 cm x 37.0 cm x 68.0 cm,87IGG03701514,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaSplit AC - Outdoor Unit94.0 cm x 37.0 cm x 68.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Split AC - Outdoor Unit,Lloyd,GLS24B32ABWA,94.0 cm x 37.0 cm x 68.0 cm,87IGG03701424,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaSplit AC - Outdoor Unit94.0 cm x 37.0 cm x 68.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Split AC - Outdoor Unit,Lloyd,GLS24B32ABWA,94.0 cm x 37.0 cm x 68.0 cm,87IGG03701554,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaSplit AC - Outdoor Unit94.0 cm x 37.0 cm x 68.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Split AC - Outdoor Unit,Lloyd,GLS24B32ABWA,94.0 cm x 37.0 cm x 68.0 cm,87IGG03701557,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaSplit AC - Outdoor Unit94.0 cm x 37.0 cm x 68.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Split AC - Outdoor Unit,Lloyd,GLS24B32ABWA,94.0 cm x 37.0 cm x 68.0 cm,87IGG03701580,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaSplit AC - Outdoor Unit94.0 cm x 37.0 cm x 68.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Split AC - Outdoor Unit,Lloyd,GLS24B32ABWA,94.0 cm x 37.0 cm x 68.0 cm,87IGG03701511,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaSplit AC - Outdoor Unit94.0 cm x 37.0 cm x 68.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Split AC - Outdoor Unit,Lloyd,GLS24B32ABWA,94.0 cm x 37.0 cm x 68.0 cm,Na,0,,1,1,,Goa Warehouse,Zone G,Ok,,Serial number sticker removed,,NaSplit AC - Outdoor Unit94.0 cm x 37.0 cm x 68.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Split AC - Outdoor Unit,Lloyd,GLS24B32ABWA,94.0 cm x 37.0 cm x 68.0 cm,Na,0,,1,1,,Goa Warehouse,Zone G,Ok,,Serial number sticker removed,,NaSplit AC - Outdoor Unit94.0 cm x 37.0 cm x 68.0 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Split AC - Outdoor Unit,Blue Star,Na,,,0,,1,1,,,,,,Ok 29.8.25,,NaSplit AC - Outdoor Unit,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Split AC - Indoor Unit,Lloyd,GLS24B32ABWA,116.1 cm x 24.0 cm x 34 cm,87IHG03706039,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaSplit AC - Indoor Unit116.1 cm x 24.0 cm x 34 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Split AC - Indoor Unit,Lloyd,GLS24B32ABWA,116.1 cm x 24.0 cm x 34 cm,87IHG03706064,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaSplit AC - Indoor Unit116.1 cm x 24.0 cm x 34 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Split AC - Indoor Unit,Lloyd,GLS24B32ABWA,116.1 cm x 24.0 cm x 34 cm,87IHG03706293,0,,1,1,,Goa Warehouse,Zone G,Ok,,Last digit of the SR cant be seen,,NaSplit AC - Indoor Unit116.1 cm x 24.0 cm x 34 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Split AC - Indoor Unit,Lloyd,GLS24B32ABWA,116.1 cm x 24.0 cm x 34 cm,87IHG03706041,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaSplit AC - Indoor Unit116.1 cm x 24.0 cm x 34 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Split AC - Indoor Unit,Lloyd,GLS24B32ABWA,116.1 cm x 24.0 cm x 34 cm,87IGG03702905,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaSplit AC - Indoor Unit116.1 cm x 24.0 cm x 34 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Split AC - Indoor Unit,Lloyd,GLS24B32ABWA,116.1 cm x 24.0 cm x 34 cm,87IGG03706058,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaSplit AC - Indoor Unit116.1 cm x 24.0 cm x 34 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Split AC - Indoor Unit,Lloyd,GLS24B32ABWA,116.1 cm x 24.0 cm x 34 cm,87IHG03706525,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaSplit AC - Indoor Unit116.1 cm x 24.0 cm x 34 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Split AC - Indoor Unit,Lloyd,GLS24B32ABWA,116.1 cm x 24.0 cm x 34 cm,87IGG03702890,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaSplit AC - Indoor Unit116.1 cm x 24.0 cm x 34 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Split AC - Indoor Unit,Lloyd,GLS24B32ABWA,116.1 cm x 24.0 cm x 34 cm,87IEG03700418,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaSplit AC - Indoor Unit116.1 cm x 24.0 cm x 34 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Split AC - Indoor Unit,Lloyd,GLS24B32ABWA,116.1 cm x 24.0 cm x 34 cm,87IGG03700809,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaSplit AC - Indoor Unit116.1 cm x 24.0 cm x 34 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Split AC - Indoor Unit,Lloyd,GLS24B32ABWA,116.1 cm x 24.0 cm x 34 cm,87IGG03700391,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,NaSplit AC - Indoor Unit116.1 cm x 24.0 cm x 34 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Split AC - Indoor Unit,Lloyd,GLS24B32ABWA,116.1 cm x 24.0 cm x 34 cm,87IHG03706045,0,,1,1,,Goa Warehouse,Zone G,Not Ok,,Was returned by the electrician in Sales Tax in 2022,,NaSplit AC - Indoor Unit116.1 cm x 24.0 cm x 34 cm,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Split AC - Indoor Unit,Blue Star,Na,,,0,,1,1,,,,,,Ok 29.8.25,,NaSplit AC - Indoor Unit,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower Air Cooler,Havells,Alitura20,"1'x1'x3'2""",EYICEIL00023,0,,1,1,,Goa Warehouse,Zone G,,,,,"NaTower Air Cooler1'x1'x3'2""",,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower Air Cooler,Havells,Alitura20,"1'x1'x3'2""",EYICEIL00056,0,,1,1,,Goa Warehouse,Zone G,,,,,"NaTower Air Cooler1'x1'x3'2""",,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower Air Cooler,Havells,Alitura20,"1'x1'x3'2""",EYICEIL00020,0,,1,1,,Goa Warehouse,Zone G,,,,,"NaTower Air Cooler1'x1'x3'2""",,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower Air Cooler,Havells,Alitura20,"1'x1'x3'2""",EYICEIL00053,0,,1,1,,Goa Warehouse,Zone G,,,,,"NaTower Air Cooler1'x1'x3'2""",,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower Air Cooler,Havells,Alitura20,"1'x1'x3'2""",EYICEIL00017,0,,1,1,,Goa Warehouse,Zone G,,,,,"NaTower Air Cooler1'x1'x3'2""",,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower Air Cooler,Havells,Alitura20,"1'x1'x3'2""",EYICEIL00059,0,,1,1,,Goa Warehouse,Zone G,,,,,"NaTower Air Cooler1'x1'x3'2""",,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower Air Cooler,Havells,Alitura20,"1'x1'x3'2""",EYICEIL00058,0,,1,1,,Goa Warehouse,Zone G,,,,,"NaTower Air Cooler1'x1'x3'2""",,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower Air Cooler,Havells,Alitura20,"1'x1'x3'2""",EYICEIL00130,0,,1,1,,Goa Warehouse,Zone G,,,,,"NaTower Air Cooler1'x1'x3'2""",,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower Air Cooler,Havells,Alitura20,"1'x1'x3'2""",EYICEIL00110,0,,1,1,,Goa Warehouse,Zone G,,,,,"NaTower Air Cooler1'x1'x3'2""",,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower Air Cooler,Havells,Alitura20,"1'x1'x3'2""",EYICEIL00138,0,,1,1,,Goa Warehouse,Zone G,,,,,"NaTower Air Cooler1'x1'x3'2""",,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower Air Cooler,Havells,Alitura20,"1'x1'x3'2""",Na,0,,1,1,,Goa Warehouse,Zone G,,,Serial number sticker removed,,"NaTower Air Cooler1'x1'x3'2""",,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower Air Cooler,Havells,Alitura20,"1'x1'x3'2""",EYICEIL00010,0,,1,1,,Goa Warehouse,Zone G,,,,,"NaTower Air Cooler1'x1'x3'2""",,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower Air Cooler,Havells,Alitura20,"1'x1'x3'2""",EYICEIL00037,0,,1,1,,Goa Warehouse,Zone G,,,,,"NaTower Air Cooler1'x1'x3'2""",,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower Air Cooler,Havells,Alitura20,"1'x1'x3'2""",EYICEIL00112,0,,1,1,,Goa Warehouse,Zone G,,,,,"NaTower Air Cooler1'x1'x3'2""",,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower Air Cooler,Havells,Alitura20,"1'x1'x3'2""",EYICEIL00133,0,,1,1,,Goa Warehouse,Zone G,,,,,"NaTower Air Cooler1'x1'x3'2""",,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower Air Cooler,Havells,Alitura20,"1'x1'x3'2""",EYICEIL00105,0,,1,1,,Goa Warehouse,Zone G,,,,,"NaTower Air Cooler1'x1'x3'2""",,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower Air Cooler,Havells,Alitura20,"1'x1'x3'2""",EYICEIL00168,0,,1,1,,Goa Warehouse,Zone G,,,,,"NaTower Air Cooler1'x1'x3'2""",,,,,,,,,,,,,,,,
Na,Technical,Appliance,Tower Air Cooler,Havells,Alitura20,"1'x1'x3'2""",EYICEIL00111,0,,1,1,,Goa Warehouse,Zone G,,,,,"NaTower Air Cooler1'x1'x3'2""",,,,,,,,,,,,,,,,
Na,Technical,Appliance,Water Cooler Hot & Cold,Voltas,Mini Magic Puret,"1'x1'x1'6""",6210305D23HS01883,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,"NaWater Cooler Hot & Cold1'x1'x1'6""",,,,,,,,,,,,,,,,
Na,Technical,Appliance,Water Cooler Hot & Cold,Voltas,Mini Magic Puret,"1'x1'x1'6""",6210305D23HS01882,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,"NaWater Cooler Hot & Cold1'x1'x1'6""",,,,,,,,,,,,,,,,
Na,Technical,Appliance,Water Cooler Hot & Cold,Voltas,Mini Magic Puret,"1'x1'x1'6""",6210305D23IS02749,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,"NaWater Cooler Hot & Cold1'x1'x1'6""",,,,,,,,,,,,,,,,
Na,Technical,Appliance,Water Cooler Hot & Cold,Voltas,Mini Magic Puret,"1'x1'x1'6""",6210305D23IS02812,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,"NaWater Cooler Hot & Cold1'x1'x1'6""",,,,,,,,,,,,,,,,
Na,Technical,Appliance,Water Cooler Hot & Cold,Voltas,Mini Magic Puret,"1'x1'x1'6""",6210305D23IS02732,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,"NaWater Cooler Hot & Cold1'x1'x1'6""",,,,,,,,,,,,,,,,
Na,Technical,Appliance,Water Cooler Hot & Cold,Voltas,Mini Magic Puret,"1'x1'x1'6""",6210305D23IS02646,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,"NaWater Cooler Hot & Cold1'x1'x1'6""",,,,,,,,,,,,,,,,
Na,Technical,Appliance,Water Cooler Hot & Cold,Voltas,Mini Magic Puret,"1'x1'x1'6""",6210305D23IS02787,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,"NaWater Cooler Hot & Cold1'x1'x1'6""",,,,,,,,,,,,,,,,
Na,Technical,Appliance,Water Cooler Hot & Cold,Voltas,Mini Magic Puret,"1'x1'x1'6""",6210305S23B002023,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,"NaWater Cooler Hot & Cold1'x1'x1'6""",,,,,,,,,,,,,,,,
Na,Technical,Appliance,Water Cooler Hot & Cold,Voltas,Mini Magic Puret,"1'x1'x1'6""",6210305S23B002116,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,"NaWater Cooler Hot & Cold1'x1'x1'6""",,,,,,,,,,,,,,,,
Na,Technical,Appliance,Water Cooler Hot & Cold,Voltas,Mini Magic Puret,"1'x1'x1'6""",6210305S23B002012,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,"NaWater Cooler Hot & Cold1'x1'x1'6""",,,,,,,,,,,,,,,,
Na,Technical,Appliance,Water Cooler Hot & Cold,Voltas,Mini Magic Puret,"1'x1'x1'6""",6210305D23GS01848,0,,1,1,,Goa Warehouse,Zone G,Ok,,,,"NaWater Cooler Hot & Cold1'x1'x1'6""",,,,,,,,,,,,,,,,
Na,Technical,Appliance,Ceiling Fans,Havells,Na,Standard,Na,0,,18,18,,Goa Warehouse,Zone H,Ok,,Sealed pack,,NaCeiling FansStandard,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Ceiling Fans,Havells,Na,Standard,Na,0,,34,34,,Goa Warehouse,Zone H,Ok,,,,NaCeiling FansStandard,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Ceiling Fans without rods,Havells,Na,Standard,Na,0,,16,16,,Goa Warehouse,Zone H,Ok,,,,NaCeiling Fans without rodsStandard,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Wall mount fans White,Orient,Na,Standard,Na,0,,8,8,,Goa Warehouse,Zone H,Ok,,,,NaWall mount fans WhiteStandard,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Black Mercado Table Fans,Anchor,Na,Standard,Na,0,,17,17,,Goa Warehouse,Zone H,Ok,,,,NaBlack Mercado Table FansStandard,,,,,,,,,,,,,,,,
Na,Technical,Appliance,Black Pedestal Fans,Local,Na,Standard,Na,0,,16,16,,Goa Warehouse,Zone H,Ok,,,,NaBlack Pedestal FansStandard,,,,,,,,,,,,,,,,
Na,Lights,Lights,Meter Box,Local,Na,Standard,Na,0,,7,7,,Goa Warehouse,Zone H,Ok,,,,NaMeter BoxStandard,,,,,,,,,,,,,,,,
Na,Lights,Lights,DB Box,Local,Na,Standard,Na,0,,16,16,,Goa Warehouse,Zone H,Ok,,,,NaDB BoxStandard,,,,,,,,,,,,,,,,
Na,Lights,Lights,Jetta Irish 250 W,Local,Na,Standard,Na,0,,19,19,,Goa Warehouse,Zone I,Ok,,,,NaJetta Irish 250 WStandard,,,,,,,,,,,,,,,,
Na,Lights,Lights,LED Par,Local,Na,Standard,Na,0,,10,10,,Goa Warehouse,Zone I,Ok,,,,NaLED ParStandard,,,,,,,,,,,,,,,,
Na,Lights,Lights,Switch + Plug,Local,Na,Standard,Na,0,,250,250,,Goa Warehouse,Zone H,Ok,,,,NaSwitch + PlugStandard,,,,,,,,,,,,,,,,
Na,Lights,Lights,Switch + Plug box,Local,Na,Standard,Na,0,,115,115,,Goa Warehouse,Zone H,Ok,,,,NaSwitch + Plug boxStandard,,,,,,,,,,,,,,,,
Na,Lights,Lights,Switch Plate,Local,Na,Standard,Na,0,,45,45,,Goa Warehouse,Zone H,Ok,,,,NaSwitch PlateStandard,,,,,,,,,,,,,,,,
Na,Lights,Lights,Surface box,Local,Na,Standard,Na,0,,104,104,,Goa Warehouse,Zone H,Ok,,,,NaSurface boxStandard,,,,,,,,,,,,,,,,
Na,Lights,Lights,Euroload Change over Switch,Local,Na,Standard,Na,0,,5,5,,Goa Warehouse,Zone H,Ok,,,,NaEuroload Change over SwitchStandard,,,,,,,,,,,,,,,,
Na,Lights,Lights,LED Drivers,Local,Na,Standard,Na,0,,10,10,,Goa Warehouse,Zone H,Ok,,,,NaLED DriversStandard,,,,,,,,,,,,,,,,
Na,Lights,Lights,Jetta Drivers 100 w,Local,Na,Standard,Na,0,,43,43,,Goa Warehouse,Zone I,Ok,,,,NaJetta Drivers 100 wStandard,,,,,,,,,,,,,,,,
Na,Lights,Lights,Jetta Drivers 200 w,Local,Na,Standard,Na,0,,28,28,,Goa Warehouse,Zone I,Ok,,,,NaJetta Drivers 200 wStandard,,,,,,,,,,,,,,,,
Na,Lights,Lights,Jetta Valor 300 w,Local,Na,Standard,Na,0,,31,31,,Goa Warehouse,Zone I,Ok,,,,NaJetta Valor 300 wStandard,,,,,,,,,,,,,,,,
Na,Lights,Lights,LED Drivers - ADS,Local,Na,Standard,Na,0,,7,7,,Goa Warehouse,Zone H,Ok,,,,NaLED Drivers - ADSStandard,,,,,,,,,,,,,,,,
Na,Lights,Lights,LED Drivers - Neon lights,Local,Na,Standard,Na,0,,21,21,,Goa Warehouse,Zone H,Ok,,,,NaLED Drivers - Neon lightsStandard,,,,,,,,,,,,,,,,
Na,Lights,Lights,Washer,Local,Na,"3'4""",Na,0,,13,13,,Goa Warehouse,Zone H,Ok,,,,"NaWasher3'4""",,,,,,,,,,,,,,,,
Na,Lights,Lights,Washer,Local,Na,"6'5""",Na,0,,12,12,,Goa Warehouse,Zone H,Ok,,,,"NaWasher6'5""",,,,,,,,,,,,,,,,
Na,Lights,Lights,Red Clamps,Local,Na,Na,Na,0,,9,9,,Goa Warehouse,Zone H,Ok,,,,NaRed ClampsNa,,,,,,,,,,,,,,,,
Na,Lights,Lights,Surface box new,Local,Na,Na,Na,0,,153,153,,Goa Warehouse,Zone H,Ok,,,,NaSurface box newNa,,,,,,,,,,,,,,,,
Na,Production,Misc.,Daku seaface post ofc,Local,Na,Standard,Na,0,,4,4,,Goa Warehouse,Zone H,Ok,,Sets of four,,NaDaku seaface post ofcStandard,,,,,,,,,,,,,,,,
Na,Production,Misc.,Metal Angles for Shelf,Local,Na,Standard,Na,0,,26,26,,Goa Warehouse,Zone H,Ok,,,,NaMetal Angles for ShelfStandard,,,,,,,,,,,,,,,,
Na,Production,Misc.,Inlit Letter Cut - THEATRE,Local,Na,Standard,Na,0,,7,7,,Goa Warehouse,Zone H,Ok,,,,NaInlit Letter Cut - THEATREStandard,,,,,,,,,,,,,,,,
Na,Production,Misc.,Inlit Letter Cut - FOUNDRY,Local,Na,Standard,Na,0,,#VALUE!,Na,,Goa Warehouse,Zone H,Ok,,Letter F was not returned,,NaInlit Letter Cut - FOUNDRYStandard,,,,,,,,,,,,,,,,
Na,Production,Misc.,Inlit Letter Cut - FOOD LAB,Local,Na,Standard,Na,0,,#VALUE!,Na,,Goa Warehouse,Zone H,Ok,,Letter F & L not returned,,NaInlit Letter Cut - FOOD LABStandard,,,,,,,,,,,,,,,,
Na,Production,Misc.,Inlit Letter Cut - THE ALAG FESTIVAL,Local,Na,Standard,Na,0,,#VALUE!,Na,,Goa Warehouse,Zone H,Ok,,"Some of the letters Damaged (S, S, A & L)",,NaInlit Letter Cut - THE ALAG FESTIVALStandard,,,,,,,,,,,,,,,,
Na,Production,Misc.,Inlit Letter Cut - Serendipity Arts Festival 2023,Local,Na,Standard,Na,0,,#VALUE!,Na,,Goa Warehouse,Zone H,Ok,,,,NaInlit Letter Cut - Serendipity Arts Festival 2023Standard,,,,,,,,,,,,,,,,
Na,Production,Misc.,Inlit Letter Cut - Serendipity Arts Festival,Local,Na,Standard,Na,0,,#VALUE!,Na,,Goa Warehouse,Zone H,Ok,,Letter S & I not returned,,NaInlit Letter Cut - Serendipity Arts FestivalStandard,,,,,,,,,,,,,,,,
Na,Production,Misc.,Curtain Rods/ Damaged,Local,Na,Standard,Na,0,,51,51,,Goa Warehouse,Zone H,Ok,,,,NaCurtain Rods/ DamagedStandard,,,,,,,,,,,,,,,,
Na,Production,Misc.,Acoustics - Curtains Blue & Black,Local,Na,"4'5""X8'10""",Na,0,,59,59,,Goa Warehouse,Zone I,Ok,,,,"NaAcoustics - Curtains Blue & Black4'5""X8'10""",,,,,,,,,,,,,,,,
Na,Production,Misc.,Acoustics - Curtains Blue & Black,Local,Na,4'X6,Na,0,,4,4,,Goa Warehouse,Zone I,Ok,,,,NaAcoustics - Curtains Blue & Black4'X6,,,,,,,,,,,,,,,,
Na,Production,Misc.,Acoustics - Curtains Blue & Black,Local,Na,4'X9',Na,0,,10,10,,Goa Warehouse,Zone I,Ok,,,,NaAcoustics - Curtains Blue & Black4'X9',,,,,,,,,,,,,,,,
Na,Production,Misc.,Acoustics - Curtains Blue & Black,Local,Na,"4'5""X8'5""",Na,0,,10,10,,Goa Warehouse,Zone I,Ok,,,,"NaAcoustics - Curtains Blue & Black4'5""X8'5""",,,,,,,,,,,,,,,,
Na,Production,Misc.,Chatai,Local,Na,Standard,Na,0,,10,10,,Goa Warehouse,Zone I,Ok,,,,NaChataiStandard,,,,,,,,,,,,,,,,
Na,Production,Misc.,Gaddas,Local,Na,Standard,Na,0,,14,14,,Goa Warehouse,Zone I,Ok,,,,NaGaddasStandard,,,,,,,,,,,,,,,,
Na,Production,Misc.,White cushioned matts,Local,Na,Standard,Na,0,,27,27,,Goa Warehouse,Zone A,Ok,,,,NaWhite cushioned mattsStandard,,,,,,,,,,,,,,,,
Na,Production,Misc.,Black cushioned matts,Local,Na,"2.3""x4'",Na,0,,95,95,,Goa Warehouse,Zone A,Ok,,,,"NaBlack cushioned matts2.3""x4'",,,,,,,,,,,,,,,,
Na,Production,Misc.,Alluminium Channels,Local,Na,"1.5""x1.5""x3'4""",Na,0,,55,55,,Goa Warehouse,Zone H,Ok,,,,"NaAlluminium Channels1.5""x1.5""x3'4""",,,,,,,,,,,,,,,,
Na,Production,Misc.,Alluminium Channels,Local,Na,"1.5""x1.5""x10'",Na,0,,28,28,,Goa Warehouse,Zone H,Ok,,,,"NaAlluminium Channels1.5""x1.5""x10'",,,,,,,,,,,,,,,,
Na,Production,Misc.,Alluminium Runner,Local,Na,"4""x8'",Na,0,,25,25,,Goa Warehouse,Zone H,Ok,,,,"NaAlluminium Runner4""x8'",,,,,,,,,,,,,,,,
Na,Production,Misc.,Bar Table,Local,Na,"7'8""x2'6""x3'10""",Na,0,,2,2,,Goa Warehouse,Zone C,Ok,,,,"NaBar Table7'8""x2'6""x3'10""",,,,,,,,,,,,,,,,
Na,Production,Misc.,Metal Pipes/ return in cut pieces,Local,Na,"18'8""",Na,0,,12,12,,Goa Warehouse,Zone A,Ok,,Not return,,"NaMetal Pipes/ return in cut pieces18'8""",,,,,,,,,,,,,,,,
Na,Production,Misc.,Safety Helmet,Local,Na,Standard,Na,0,,6,6,,Goa Warehouse,Zone H,Ok,,,,NaSafety HelmetStandard,,,,,,,,,,,,,,,,
Na,Production,Misc.,Grey Carpet Roll,Na,Na,Na,Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,,,NaGrey Carpet RollNa,,,,,,,,,,,,,,,,
Na,Production,Misc.,Grass Carpet,Local,Na,"16'8""x 6'10",Na,0,,1,1,,Goa Warehouse,Zone A,Ok,,Not return,,"NaGrass Carpet16'8""x 6'10",,,,,,,,,,,,,,,,
Na,Production,Misc.,Metal Frame Trolley,Local,Na,Standard,Na,0,,1,1,,Goa Warehouse,Zone I,Ok,,,,NaMetal Frame TrolleyStandard,,,,,,,,,,,,,,,,
Na,Production,Misc.,Lamp lighting,Local,Na,5',Na,0,,1,1,,Goa Warehouse,Zone D,Ok,,,,NaLamp lighting5',,,,,,,,,,,,,,,,
Na,Production,Misc.,Lamp lighting,Local,Na,3',Na,0,,1,1,,Goa Warehouse,Zone D,Ok,,,,NaLamp lighting3',,,,,,,,,,,,,,,,
Na,Production,Misc.,Cueue Manager,Local,Na,Standard,Na,0,,80,80,,Goa Warehouse,Zone D,Ok,,,,NaCueue ManagerStandard,,,,,,,,,,,,,,,,
Na,Production,Misc.,Metal Wheeled Base,Local,Na,"1'6""x1'6"" x2'6",Na,0,,2,2,,Goa Warehouse,Zone I,Ok,,,,"NaMetal Wheeled Base1'6""x1'6"" x2'6",,,,,,,,,,,,,,,,
Na,Production,Misc.,Metal Frame with lights,Local,Na,"8'x1'6""x5'6""",Na,0,,1,1,,Goa Warehouse,Zone I,Ok,,,,"NaMetal Frame with lights8'x1'6""x5'6""",,,,,,,,,,,,,,,,
Na,Production,Artwork,Sambha Square Roof,Local,Na,Na,Na,0,,2,2,,Goa Warehouse,Zone A,Ok,,,,NaSambha Square RoofNa,,,,,,,,,,,,,,,,
Na,Production,Misc.,Bins,Ikea,Na,Na,Na,0,,6,6,,Goa Warehouse,Zone D,Ok,,,,NaBinsNa,,,,,,,,,,,,,,,,
Na,Production,Tools,Trunks,Local,Na,Na,Na,0,,5,5,,Goa Warehouse,Zone H,Ok,,,,NaTrunksNa,,,,,,,,,,,,,,,,
Na,Production,Misc.,Lights box - black,Local,Na,"2'x8""x8""",Na,0,,3,3,,Goa Warehouse,Zone I,Ok,,,,"NaLights box - black2'x8""x8""",,,,,,,,,,,,,,,,
Na,Production,Misc.,Black Frame with Base,Local,Na,"5'x1'4""x5'3""",Na,0,,1,1,,Goa Warehouse,Zone I,Ok,,,,"NaBlack Frame with Base5'x1'4""x5'3""",,,,,,,,,,,,,,,,
Na,Production,Misc.,Wooden Pallets,Na,Na,4'X4',Na,0,,560,560,,Goa Warehouse,Zone E,Ok,,,,NaWooden Pallets4'X4',,,,,,,,,,,,,,,,
Na,Technical,Appliance,Refrigerator,Na,Na,Na,Na,0,,1,1,,Goa Warehouse,Zone E,Ok,,,,NaRefrigeratorNa,,,,,,,,,,,,,,,,
Na,Lights,Lights,Lineate,Havells,Na,Na,Na,0,,12,12,,Delhi Warehouse,To be defined,,,,,NaLineateNa,,,,,,,,,,,,,,,,
Na,Lights,Lights,Tracks,Eutrck,Na,Na,Na,0,,183,183,,Delhi Warehouse,To be defined,,,,,NaTracksNa,,,,,,,,,,,,,,,,
Na,Lights,Lights,Track End Connector,Eutrck,Na,Na,Na,0,,170,170,,Delhi Warehouse,To be defined,,,after 2024 festival return back is 74 only,,NaTrack End ConnectorNa,,,,,,,,,,,,,,,,
Na,Lights,Lights,Track Power Supply,Eutrck,Na,Na,Na,0,,95,95,,Delhi Warehouse,To be defined,,,,,NaTrack Power SupplyNa,,,,,,,,,,,,,,,,
Na,Lights,Lights,Jetta Valor 300w,Havells,Na,Na,Na,0,,9,9,,Delhi Warehouse,To be defined,,,,,NaJetta Valor 300wNa,,,,,,,,,,,,,,,,
Na,Lights,Lights,Jetta Irish 100w,Havells,Na,Na,Na,0,,2,2,,Delhi Warehouse,To be defined,,,,,NaJetta Irish 100wNa,,,,,,,,,,,,,,,,
Na,Lights,Lights,Jetta 45w Flood Light,Havells,Na,Na,Na,0,,5,5,,Delhi Warehouse,To be defined,,,,,NaJetta 45w Flood LightNa,,,,,,,,,,,,,,,,
Na,Lights,Lights,Corvi Light,Havells,Na,Na,Na,0,,204,204,,Delhi Warehouse,To be defined,,,,,NaCorvi LightNa,,,,,,,,,,,,,,,,
Na,Lights,Lights,LED Baton,Panasonic,Na,Na,Na,0,,82,82,,Delhi Warehouse,To be defined,,,,,NaLED BatonNa,,,,,,,,,,,,,,,,
Na,Lights,Lights,Tube Light,Philips,Na,Na,Na,0,,26,26,,Delhi Warehouse,To be defined,,,,,NaTube LightNa,,,,,,,,,,,,,,,,
Na,Lights,Lights,LED Baton,Philips,Na,Na,Na,0,,38,38,,Delhi Warehouse,To be defined,,,,,NaLED BatonNa,,,,,,,,,,,,,,,,
Na,Lights,Lights,LED Baton,Bajaj,Na,Na,Na,0,,21,21,,Delhi Warehouse,To be defined,,,,,NaLED BatonNa,,,,,,,,,,,,,,,,
Na,Lights,Lights,LED Baton,Syska,Na,Na,Na,0,,3,3,,Delhi Warehouse,To be defined,,,,,NaSyskaNa,,,,,,,,,,,,,,,,
Na,Lights,Lights,LED Baton,Havells,Na,Na,Na,0,,11,11,,Delhi Warehouse,To be defined,,,,,NaLED BatonNa,,,,,,,,,,,,,,,,
Na,Lights,Lights,LED Baton,Opulus,Na,Na,Na,0,,14,14,,Delhi Warehouse,To be defined,,,,,NaLED BatonNa,,,,,,,,,,,,,,,,
Na,Production,misc.,Sambha Ladak,Na,Na,Na,Na,0,,1,1,,Goa Warehouse,Zone B,Not Ok,,,,NaSambha LadakNa,,,,,,,,,,,,,,,,
Na,Production,misc.,Wooden Table With Cavities,Na,Na,"7'.5""x3'.6""x2'.5 """,Na,0,,2,2,,Goa Warehouse,Zone E,Ok,,One of the table has damaged corner(both to be refurbished),,"NaWooden Table With Cavities7'.5""x3'.6""x2'.5 """,,,,,,,,,,,,,,,,
Na,Production,misc,Metal Stand,Na,Na,"7'x2'.3""",Na,0,,3,3,,Goa Warehouse,Zone E,Ok,,,,"NaMetal Stand7'x2'.3""",,,,,,,,,,,,,,,,
Na,Production,misc.,Grey Metal Plate,Na,Na,"7"".4""x1'.2""",Na,0,,1,1,,Goa Warehouse,zone E,Ok,,,,"NaGrey Metal Plate7"".4""x1'.2""",,,,,,,,,,,,,,,,
Na,Production,misc.,Metal Grid,Na,Na,"12'x3'.3""",Na,0,,1,1,,Goa Warehouse,Zone I,Ok,,,,"NaMetal Grid12'x3'.3""",,,,,,,,,,,,,,,,
Na,Production,misc.,Metal Grid for Tv,Na,Na,"3'.6""x1'x7'",Na,0,,1,1,,Goa Warehouse,ZoneI,Ok,,,,"NaMetal Grid for Tv3'.6""x1'x7'",,,,,,,,,,,,,,,,
Na,Production,Misc.,Notice Board,Na,Na,"10'x5'.5""",Na,0,,1,1,,Goa Warehouse,zone E,Ok,,,,"NaNotice Board10'x5'.5""",,,,,,,,,,,,,,,,
Na,Production,Misc.,Round Table,Na,Na,"3'x3'x2'.6""",Na,0,,1,1,,Goa Warehouse,zone E,Ok,,,,"NaRound Table3'x3'x2'.6""",,,,,,,,,,,,,,,,
Na,Production,Misc.,Woofer Case,Na,Na,"1'.8""x1'.6""x1'.8""",Na,0,,1,1,,Goa Warehouse,zone E,Ok,,,,"NaWoofer Case1'.8""x1'.6""x1'.8""",,,,,,,,,,,,,,,,
Na,Production,Misc.,Blue Pedestal,Na,Na,1x1x3,Na,0,,2,2,,Goa Warehouse,zone B,Ok,,,,NaBlue Pedestal1x1x3,,,,,,,,,,,,,,,,
Na,Production,Misc.,White Table With Storage,Na,Na,"6'.5""x2'x2'.8""",Na,0,,1,1,,Goa Warehouse,zone C,Ok,,,,"NaWhite Table With Storage6'.5""x2'x2'.8""",,,,,,,,,,,,,,,,
Na,Production,Misc.,White Pedestal,Na,Na,"8'x2'8""x3'x2""",Na,0,,1,1,,Goa Warehouse,zone C,Ok,,,,"NaWhite Pedestal8'x2'8""x3'x2""",,,,,,,,,,,,,,,,
Na,Production,Misc.,White Pedestal,Na,Na,"6'x2'x3'2""",Na,0,,1,1,,Goa Warehouse,zone C,Ok,,,,"NaWhite Pedestal6'x2'x3'2""",,,,,,,,,,,,,,,,
Na,Production,Misc.,White Desk With Storage,Na,Na,"5'x2'x2'.6""",Na,0,,4,4,,Goa Warehouse,zone C,Ok,,,,"NaWhite Desk With Storage5'x2'x2'.6""",,,,,,,,,,,,,,,,
Na,Production,Misc.,Venue Marker 2024,Na,Na,"3'.3""x1'x3'",Na,0,,35,35,,Goa Warehouse,zone C,Ok,,,,"NaVenue Marker 20243'.3""x1'x3'",,,,,,,,,,,,,,,,
Na,Production,Misc.,Treffic Cone,Na,Na,"3'.3""x1'x3'",Na,0,,117,117,,Goa Warehouse,zone C,,,,,"NaTreffic Cone3'.3""x1'x3'",,,,,,,,,,,,,,,,
Na,Production,Misc.,Mudda,Na,Na,Na,Na,0,,96,96,,Goa Warehouse,zone C,Ok,,,,NaMuddaNa,,,,,,,,,,,,,,,,`;

function parseCsvLine(line) {
  const result = [];
  let current = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const char = line[i];
    if (char === '"') {
      if (inQuotes && line[i + 1] === '"') {
        current += '"';
        i++;
      } else {
        inQuotes = !inQuotes;
      }
    } else if (char === ',' && !inQuotes) {
      result.push(current);
      current = '';
    } else {
      current += char;
    }
  }
  result.push(current);
  return result;
}

async function seedProductionInventory() {
  console.log('Seeding Production Inventory Items...');
  
  // Get active event
  let event = await prisma.event.findFirst({ where: { status: 'Active' } });
  if (!event) event = await prisma.event.findFirst();
  if (!event) {
    console.error('No active event found');
    process.exit(1);
  }
  const eventId = event.id;

  const lines = rawCsv.split('\n').filter(l => l.trim().length > 0);
  // Skip header line
  const dataLines = lines.slice(1);

  let insertedCount = 0;
  let codeIndex = 1;

  for (const line of dataLines) {
    const cols = parseCsvLine(line);
    if (cols.length < 5) continue;

    const rawSafCode = cols[0] ? cols[0].trim() : 'Na';
    const inventoryCategory = cols[1] ? cols[1].trim() : 'Production';
    const subCategory = cols[2] ? cols[2].trim() : 'General';
    const element = cols[3] ? cols[3].trim() : 'Item';
    const brandProject = cols[4] ? cols[4].trim() : 'Na';
    const model = cols[5] ? cols[5].trim() : 'Na';
    const sizeLwh = cols[6] ? cols[6].trim() : 'Na';
    const serialNo = cols[7] ? cols[7].trim() : 'Na';
    const totalQtyStr = cols[11] ? cols[11].trim() : '1';
    let totalQuantity = parseInt(totalQtyStr);
    if (isNaN(totalQuantity) || totalQuantity < 0) totalQuantity = 1;

    const location = cols[13] ? cols[13].trim() : 'Delhi Warehouse';
    const zone = cols[14] ? cols[14].trim() : 'To be defined';
    const condition = cols[15] ? cols[15].trim() : 'Ok';
    const throwRatio = cols[16] ? cols[16].trim() : 'Na';
    let remarks = cols[17] ? cols[17].trim() : '';

    if (zone && zone !== 'To be defined' && zone !== 'Na') {
      remarks = remarks ? `${remarks} | Zone: ${zone}` : `Zone: ${zone}`;
    }

    const safCode = rawSafCode !== 'Na' ? rawSafCode : `PRD-${String(codeIndex++).padStart(4, '0')}`;
    const assetId = `PROD-${String(insertedCount + 1).padStart(6, '0')}`;

    // Check if safCode already exists for this event
    const existing = await prisma.inventoryItem.findFirst({
      where: { eventId, safCode }
    });

    if (existing) {
      // Update existing item
      await prisma.inventoryItem.update({
        where: { id: existing.id },
        data: {
          inventoryCategory,
          subCategory,
          element,
          brandProject,
          model,
          sizeLwh,
          serialNo,
          totalQuantity,
          availableQuantity: totalQuantity - existing.allocatedQuantity,
          location: `${location}${zone ? ` (${zone})` : ''}`,
          condition: condition === 'Bad' || condition === 'Not Ok' ? 'Damaged / Refurbish Required' : condition,
          remarks,
          inventoryUsageType: 'PRODUCTION'
        }
      });
    } else {
      await prisma.inventoryItem.create({
        data: {
          eventId,
          safCode,
          inventoryCategory: inventoryCategory || 'Production',
          subCategory: subCategory || 'General',
          element,
          yearOfPurchase: '2026',
          brandProject: brandProject || 'Na',
          model: model || 'Na',
          sizeLwh: sizeLwh || 'Na',
          uom: 'Nos',
          serialNo: serialNo || 'Na',
          totalQuantity,
          reservedQuantity: 0,
          allocatedQuantity: 0,
          damagedQuantity: condition === 'Bad' || condition === 'Not Ok' ? 1 : 0,
          maintenanceQuantity: 0,
          availableQuantity: totalQuantity,
          location: location ? `${location}${zone && zone !== 'To be defined' ? ` (${zone})` : ''}` : 'Goa Warehouse',
          condition: condition === 'Bad' || condition === 'Not Ok' ? 'Damaged' : condition,
          throwRatio: throwRatio || 'Na',
          remarks: remarks || '',
          inventoryUsageType: 'PRODUCTION',
          inventorySource: 'Owned',
          ownershipType: 'SAF',
          assetId,
          createdBy: 'Production Team'
        }
      });
    }
    insertedCount++;
  }

  console.log(`Successfully processed and inserted ${insertedCount} Production Team inventory items!`);
}

seedProductionInventory()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
